# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class CognitiveAccountRaiPolicyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :base_policy_name, T::String
    attribute :cognitive_account_id, T::String
    attribute :content_filter, T::Array.of(T::Hash)
    attribute :name, T::String
    attribute? :mode, T::String.optional
    attribute? :tags, T::Hash.optional
  end
end
