# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_batch_account/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureBatchAccount
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_batch_account,
      attributes_class: Azure::Types::BatchAccountAttributes,
      outputs: { id: :id },
      map: [:location, :name, :resource_group_name],
      map_present: [:encryption, :identity, :key_vault_reference, :network_profile, :pool_allocation_mode, :storage_account_authentication_mode, :storage_account_id, :storage_account_node_identity, :tags],
      map_bool: [:public_network_access_enabled]
  end
  module Azure
    include AzureBatchAccount
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
