# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_maintenance_configuration/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureMaintenanceConfiguration
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_maintenance_configuration,
      attributes_class: Azure::Types::MaintenanceConfigurationAttributes,
      outputs: { id: :id },
      map: [:location, :name, :resource_group_name, :scope],
      map_present: [:in_guest_user_patch_mode, :install_patches, :properties, :tags, :visibility, :window]
  end
  module Azure
    include AzureMaintenanceConfiguration
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
