# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_stream_analytics_output_synapse/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureStreamAnalyticsOutputSynapse
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_stream_analytics_output_synapse,
      attributes_class: Azure::Types::StreamAnalyticsOutputSynapseAttributes,
      outputs: { id: :id },
      map: [:database, :name, :password, :resource_group_name, :server, :stream_analytics_job_name, :table, :user]
  end
  module Azure
    include AzureStreamAnalyticsOutputSynapse
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
