# Code generated by pangea-forge.
# InSpec profile for verifying azurerm_stack_hci_extension infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AZURERM_TOKEN and AZURERM_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/azurerm_stack_hci_extension/ -t azurerm://

control 'azurerm_stack_hci_extension-exists' do
  impact 1.0
  title 'Manages a azurerm_stack_hci_extension resource'
  desc 'Verify that the azurerm_stack_hci_extension resource exists and has expected properties'

  describe azurerm_stack_hci_extension(name: attribute('id')) do
    it { should exist }
    its('arc_setting_id') { should_not be_nil }
    its('name') { should_not be_nil }
    its('publisher') { should_not be_nil }
    its('type') { should_not be_nil }
  end
end
