# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class NetappVolumeAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Azure::Types

    attribute :account_name, T::String
    attribute :location, T::String
    attribute :name, T::String
    attribute :pool_name, T::String
    attribute :resource_group_name, T::String
    attribute :service_level, T::String
    attribute :storage_quota_in_gb, (T::Coercible::Integer | T::Coercible::Float)
    attribute :subnet_id, T::String
    attribute :volume_path, T::String
    attribute? :accept_grow_capacity_pool_for_short_term_clone_split, T::String.optional
    attribute? :azure_vmware_data_store_enabled, T::Bool.optional
    attribute? :cool_access, T::Hash.optional
    attribute? :create_from_snapshot_resource_id, T::String.optional
    attribute? :data_protection_advanced_ransomware, T::Hash.optional
    attribute? :data_protection_backup_policy, T::Hash.optional
    attribute? :data_protection_replication, T::Hash.optional
    attribute? :data_protection_snapshot_policy, T::Hash.optional
    attribute? :encryption_key_source, T::String.optional
    attribute? :export_policy_rule, T::Array.of(T::Hash).optional
    attribute? :kerberos_enabled, T::Bool.optional
    attribute? :key_vault_private_endpoint_id, T::String.optional
    attribute? :large_volume_enabled, T::Bool.optional
    attribute? :network_features, T::String.optional
    attribute? :protocols, T::Array.of(T::String).optional
    attribute? :security_style, T::String.optional
    attribute? :smb3_protocol_encryption_enabled, T::Bool.optional
    attribute? :smb_access_based_enumeration_enabled, T::Bool.optional
    attribute? :smb_continuous_availability_enabled, T::Bool.optional
    attribute? :smb_non_browsable_enabled, T::Bool.optional
    attribute? :snapshot_directory_visible, T::Bool.optional
    attribute? :tags, T::Hash.optional
    attribute? :throughput_in_mibps, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :zone, T::String.optional
  end
end
