# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_postgresql_flexible_server/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzurePostgresqlFlexibleServer
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_postgresql_flexible_server,
      attributes_class: Azure::Types::PostgresqlFlexibleServerAttributes,
      outputs: { id: :id },
      map: [:location, :name, :resource_group_name],
      map_present: [:administrator_login, :administrator_password, :administrator_password_wo, :administrator_password_wo_version, :authentication, :backup_retention_days, :cluster, :create_mode, :customer_managed_key, :delegated_subnet_id, :high_availability, :identity, :maintenance_window, :point_in_time_restore_time_in_utc, :private_dns_zone_id, :replication_role, :sku_name, :source_server_id, :storage_mb, :storage_tier, :tags, :version, :zone],
      map_bool: [:auto_grow_enabled, :geo_redundant_backup_enabled, :public_network_access_enabled]
  end
  module Azure
    include AzurePostgresqlFlexibleServer
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
