# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_eventgrid_partner_registration/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureEventgridPartnerRegistration
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_eventgrid_partner_registration,
      attributes_class: Azure::Types::EventgridPartnerRegistrationAttributes,
      outputs: { id: :id },
      map: [:name, :resource_group_name],
      map_present: [:tags]
  end
  module Azure
    include AzureEventgridPartnerRegistration
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
