# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_sentinel_data_connector_office_power_bi/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureSentinelDataConnectorOfficePowerBi
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_sentinel_data_connector_office_power_bi,
      attributes_class: Azure::Types::SentinelDataConnectorOfficePowerBiAttributes,
      outputs: { id: :id },
      map: [:log_analytics_workspace_id, :name],
      map_present: [:tenant_id]
  end
  module Azure
    include AzureSentinelDataConnectorOfficePowerBi
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
