# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class HealthcareMedtechServiceFhirDestinationAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Azure::Types

    attribute :destination_fhir_mapping_json, T::String
    attribute :destination_fhir_service_id, T::String
    attribute :destination_identity_resolution_type, T::String
    attribute :location, T::String
    attribute :medtech_service_id, T::String
    attribute :name, T::String
  end
end
