# Code generated by pangea-forge.
# InSpec profile for verifying azurerm_network_security_perimeter_association infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AZURERM_TOKEN and AZURERM_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/azurerm_network_security_perimeter_association/ -t azurerm://

control 'azurerm_network_security_perimeter_association-exists' do
  impact 1.0
  title 'Manages a azurerm_network_security_perimeter_association resource'
  desc 'Verify that the azurerm_network_security_perimeter_association resource exists and has expected properties'

  describe azurerm_network_security_perimeter_association(name: attribute('id')) do
    it { should exist }
    its('access_mode') { should_not be_nil }
    its('name') { should_not be_nil }
    its('network_security_perimeter_profile_id') { should_not be_nil }
    its('resource_id') { should_not be_nil }
  end
end
