# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class EventhubNamespaceCustomerManagedKeyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :eventhub_namespace_id, T::String
    attribute :key_vault_key_ids, T::Array.of(T::String)
    attribute? :infrastructure_encryption_enabled, T::Bool.optional
    attribute? :user_assigned_identity_id, T::String.optional
  end
end
