# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_private_dns_mx_record/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzurePrivateDnsMxRecord
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_private_dns_mx_record,
      attributes_class: Azure::Types::PrivateDnsMxRecordAttributes,
      outputs: { id: :id },
      map: [:record, :resource_group_name, :ttl, :zone_name],
      map_present: [:name, :tags]
  end
  module Azure
    include AzurePrivateDnsMxRecord
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
