# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_monitor_autoscale_setting/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureMonitorAutoscaleSetting
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_monitor_autoscale_setting,
      attributes_class: Azure::Types::MonitorAutoscaleSettingAttributes,
      outputs: { id: :id },
      map: [:location, :name, :profile, :resource_group_name, :target_resource_id],
      map_present: [:notification, :predictive, :tags],
      map_bool: [:enabled]
  end
  module Azure
    include AzureMonitorAutoscaleSetting
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
