# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_cosmosdb_sql_role_assignment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureCosmosdbSqlRoleAssignment
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_cosmosdb_sql_role_assignment,
      attributes_class: Azure::Types::CosmosdbSqlRoleAssignmentAttributes,
      outputs: { id: :id },
      map: [:account_name, :principal_id, :resource_group_name, :role_definition_id, :scope]
  end
  module Azure
    include AzureCosmosdbSqlRoleAssignment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
