# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class NotificationHubNamespaceAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Azure::Types

    attribute :location, T::String
    attribute :name, T::String
    attribute :namespace_type, T::String
    attribute :resource_group_name, T::String
    attribute :sku_name, T::String
    attribute? :enabled, T::Bool.optional
    attribute? :replication_region, T::String.optional
    attribute? :tags, T::Hash.optional
    attribute? :zone_redundancy_enabled, T::Bool.optional
  end
end
