# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class StackHciNetworkInterfaceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :custom_location_id, T::String
    attribute :ip_configuration, T::Array.of(T::Hash)
    attribute :location, T::String
    attribute :name, T::String
    attribute :resource_group_name, T::String
    attribute? :dns_servers, T::Array.of(T::String).optional
    attribute? :mac_address, T::String.optional
    attribute? :tags, T::Hash.optional
  end
end
