# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_hpc_cache_access_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureHpcCacheAccessPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_hpc_cache_access_policy,
      attributes_class: Azure::Types::HpcCacheAccessPolicyAttributes,
      outputs: { id: :id },
      map: [:access_rule, :hpc_cache_id, :name]
  end
  module Azure
    include AzureHpcCacheAccessPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
