# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_api_management_notification_recipient_user/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureApiManagementNotificationRecipientUser
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_api_management_notification_recipient_user,
      attributes_class: Azure::Types::ApiManagementNotificationRecipientUserAttributes,
      outputs: { id: :id },
      map: [:api_management_id, :notification_type, :user_id]
  end
  module Azure
    include AzureApiManagementNotificationRecipientUser
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
