# Code generated by pangea-forge.
# InSpec profile for verifying azurerm_maintenance_assignment_virtual_machine infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AZURERM_TOKEN and AZURERM_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/azurerm_maintenance_assignment_virtual_machine/ -t azurerm://

control 'azurerm_maintenance_assignment_virtual_machine-exists' do
  impact 1.0
  title 'Manages a azurerm_maintenance_assignment_virtual_machine resource'
  desc 'Verify that the azurerm_maintenance_assignment_virtual_machine resource exists and has expected properties'

  describe azurerm_maintenance_assignment_virtual_machine(name: attribute('id')) do
    it { should exist }
    its('location') { should_not be_nil }
    its('maintenance_configuration_id') { should_not be_nil }
    its('virtual_machine_id') { should_not be_nil }
  end
end
