# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class OracleAutonomousDatabaseBackupAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Azure::Types

    attribute :autonomous_database_id, T::String
    attribute :name, T::String
    attribute :retention_period_in_days, (T::Coercible::Integer | T::Coercible::Float)
    attribute? :type, T::String.optional
  end
end
