# Code generated by pangea-forge.
# InSpec profile for verifying azurerm_iothub_endpoint_cosmosdb_account infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AZURERM_TOKEN and AZURERM_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/azurerm_iothub_endpoint_cosmosdb_account/ -t azurerm://

control 'azurerm_iothub_endpoint_cosmosdb_account-exists' do
  impact 1.0
  title 'Manages a azurerm_iothub_endpoint_cosmosdb_account resource'
  desc 'Verify that the azurerm_iothub_endpoint_cosmosdb_account resource exists and has expected properties'

  describe azurerm_iothub_endpoint_cosmosdb_account(name: attribute('id')) do
    it { should exist }
    its('container_name') { should_not be_nil }
    its('database_name') { should_not be_nil }
    its('endpoint_uri') { should_not be_nil }
    its('iothub_id') { should_not be_nil }
    its('name') { should_not be_nil }
    its('resource_group_name') { should_not be_nil }
  end
end
