# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_data_factory/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureDataFactory
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_data_factory,
      attributes_class: Azure::Types::DataFactoryAttributes,
      outputs: { id: :id },
      map: [:location, :name, :resource_group_name],
      map_present: [:github_configuration, :global_parameter, :identity, :purview_id, :tags, :vsts_configuration],
      map_bool: [:managed_virtual_network_enabled, :public_network_enabled]
  end
  module Azure
    include AzureDataFactory
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
