# Code generated by pangea-forge.
# InSpec profile for verifying azurerm_site_recovery_services_vault_hyperv_site infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AZURERM_TOKEN and AZURERM_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/azurerm_site_recovery_services_vault_hyperv_site/ -t azurerm://

control 'azurerm_site_recovery_services_vault_hyperv_site-exists' do
  impact 1.0
  title 'Manages a azurerm_site_recovery_services_vault_hyperv_site resource'
  desc 'Verify that the azurerm_site_recovery_services_vault_hyperv_site resource exists and has expected properties'

  describe azurerm_site_recovery_services_vault_hyperv_site(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
    its('recovery_vault_id') { should_not be_nil }
  end
end
