# Code generated by pangea-forge.
# InSpec profile for verifying azurerm_postgresql_flexible_server_configuration infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AZURERM_TOKEN and AZURERM_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/azurerm_postgresql_flexible_server_configuration/ -t azurerm://

control 'azurerm_postgresql_flexible_server_configuration-exists' do
  impact 1.0
  title 'Manages a azurerm_postgresql_flexible_server_configuration resource'
  desc 'Verify that the azurerm_postgresql_flexible_server_configuration resource exists and has expected properties'

  describe azurerm_postgresql_flexible_server_configuration(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
    its('server_id') { should_not be_nil }
    its('value') { should_not be_nil }
  end
end
