# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_arc_machine_extension/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureArcMachineExtension
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_arc_machine_extension,
      attributes_class: Azure::Types::ArcMachineExtensionAttributes,
      outputs: { id: :id },
      map: [:arc_machine_id, :location, :name, :publisher, :type],
      map_present: [:force_update_tag, :protected_settings, :settings, :tags, :type_handler_version],
      map_bool: [:automatic_upgrade_enabled]
  end
  module Azure
    include AzureArcMachineExtension
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
