# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_web_pubsub_hub/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureWebPubsubHub
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_web_pubsub_hub,
      attributes_class: Azure::Types::WebPubsubHubAttributes,
      outputs: { id: :id },
      map: [:name, :web_pubsub_id],
      map_present: [:event_handler, :event_listener],
      map_bool: [:anonymous_connections_enabled]
  end
  module Azure
    include AzureWebPubsubHub
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
