# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_function_app/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureFunctionApp
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_function_app,
      attributes_class: Azure::Types::FunctionAppAttributes,
      outputs: { id: :id },
      map: [:app_service_plan_id, :location, :name, :resource_group_name, :storage_account_access_key, :storage_account_name],
      map_present: [:auth_settings, :client_cert_mode, :connection_string, :daily_memory_time_quota, :identity, :os_type, :site_config, :source_control, :tags, :version],
      map_bool: [:enable_builtin_logging, :enabled, :https_only]
  end
  module Azure
    include AzureFunctionApp
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
