# Code generated by pangea-forge.
# InSpec profile for verifying azurerm_cosmosdb_sql_role_assignment infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AZURERM_TOKEN and AZURERM_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/azurerm_cosmosdb_sql_role_assignment/ -t azurerm://

control 'azurerm_cosmosdb_sql_role_assignment-exists' do
  impact 1.0
  title 'Manages a azurerm_cosmosdb_sql_role_assignment resource'
  desc 'Verify that the azurerm_cosmosdb_sql_role_assignment resource exists and has expected properties'

  describe azurerm_cosmosdb_sql_role_assignment(name: attribute('id')) do
    it { should exist }
    its('account_name') { should_not be_nil }
    its('principal_id') { should_not be_nil }
    its('resource_group_name') { should_not be_nil }
    its('role_definition_id') { should_not be_nil }
    its('scope') { should_not be_nil }
  end
end
