# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class PimActiveRoleAssignmentAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Azure::Types

    attribute :principal_id, T::String
    attribute :role_definition_id, T::String
    attribute :scope, T::String
    attribute? :justification, T::String.optional
    attribute? :schedule, T::Hash.optional
    attribute? :ticket, T::Hash.optional
  end
end
