# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class MssqlServerAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :location, T::String
    attribute :name, T::String
    attribute :resource_group_name, T::String
    attribute :version, T::String
    attribute? :administrator_login_password, T::String.optional
    attribute? :administrator_login_password_wo, T::String.optional
    attribute? :administrator_login_password_wo_version, T::Float.optional
    attribute? :azuread_administrator, T::Array.of(T::Hash).optional
    attribute? :connection_policy, T::String.optional
    attribute? :express_vulnerability_assessment_enabled, T::Bool.optional
    attribute? :identity, T::Array.of(T::Hash).optional
    attribute? :minimum_tls_version, T::String.optional
    attribute? :outbound_network_restriction_enabled, T::Bool.optional
    attribute? :public_network_access_enabled, T::Bool.optional
    attribute? :tags, T::Hash.optional
    attribute? :transparent_data_encryption_key_vault_key_id, T::String.optional
  end
end
