# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_data_factory_linked_service_web/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureDataFactoryLinkedServiceWeb
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_data_factory_linked_service_web,
      attributes_class: Azure::Types::DataFactoryLinkedServiceWebAttributes,
      outputs: { id: :id },
      map: [:authentication_type, :data_factory_id, :name, :url],
      map_present: [:additional_properties, :annotations, :description, :integration_runtime_name, :parameters, :password, :username]
  end
  module Azure
    include AzureDataFactoryLinkedServiceWeb
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
