# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class DevCenterCatalogAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Azure::Types

    attribute :dev_center_id, T::String
    attribute :name, T::String
    attribute :resource_group_name, T::String
    attribute? :catalog_adogit, T::Hash.optional
    attribute? :catalog_github, T::Hash.optional
  end
end
