# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_federated_identity_credential/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureFederatedIdentityCredential
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_federated_identity_credential,
      attributes_class: Azure::Types::FederatedIdentityCredentialAttributes,
      outputs: { id: :id },
      map: [:audience, :issuer, :name, :subject]
  end
  module Azure
    include AzureFederatedIdentityCredential
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
