# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class KubernetesFleetUpdateStrategyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :kubernetes_fleet_manager_id, T::String
    attribute :name, T::String
    attribute :stage, T::Array.of(T::Hash)
  end
end
