# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class SentinelDataConnectorAwsS3Attributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :aws_role_arn, T::String
    attribute :destination_table, T::String
    attribute :log_analytics_workspace_id, T::String
    attribute :name, T::String
    attribute :sqs_urls, T::Array.of(T::String)
  end
end
