# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class VmwarePrivateCloudAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :location, T::String
    attribute :management_cluster, T::Array.of(T::Hash)
    attribute :name, T::String
    attribute :network_subnet_cidr, T::String
    attribute :resource_group_name, T::String
    attribute :sku_name, T::String
    attribute? :internet_connection_enabled, T::Bool.optional
    attribute? :nsxt_password, T::String.optional
    attribute? :tags, T::Hash.optional
    attribute? :vcenter_password, T::String.optional
  end
end
