# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_sentinel_data_connector_azure_active_directory/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureSentinelDataConnectorAzureActiveDirectory
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_sentinel_data_connector_azure_active_directory,
      attributes_class: Azure::Types::SentinelDataConnectorAzureActiveDirectoryAttributes,
      outputs: { id: :id },
      map: [:log_analytics_workspace_id, :name]
  end
  module Azure
    include AzureSentinelDataConnectorAzureActiveDirectory
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
