# Code generated by pangea-forge.
# InSpec profile for verifying azurerm_virtual_desktop_workspace_application_group_association infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AZURERM_TOKEN and AZURERM_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/azurerm_virtual_desktop_workspace_application_group_association/ -t azurerm://

control 'azurerm_virtual_desktop_workspace_application_group_association-exists' do
  impact 1.0
  title 'Manages a azurerm_virtual_desktop_workspace_application_group_association resource'
  desc 'Verify that the azurerm_virtual_desktop_workspace_application_group_association resource exists and has expected properties'

  describe azurerm_virtual_desktop_workspace_application_group_association(name: attribute('id')) do
    it { should exist }
    its('application_group_id') { should_not be_nil }
    its('workspace_id') { should_not be_nil }
  end
end
