# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class KustoClusterPrincipalAssignmentAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Azure::Types

    attribute :cluster_name, T::String
    attribute :name, T::String
    attribute :principal_id, T::String
    attribute :principal_type, T::String
    attribute :resource_group_name, T::String
    attribute :role, T::String
    attribute :tenant_id, T::String
  end
end
