# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class DatadogMonitorAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :datadog_organization, T::Array.of(T::Hash)
    attribute :location, T::String
    attribute :name, T::String
    attribute :resource_group_name, T::String
    attribute :sku_name, T::String
    attribute :user, T::Array.of(T::Hash)
    attribute? :identity, T::Array.of(T::Hash).optional
    attribute? :monitoring_enabled, T::Bool.optional
    attribute? :tags, T::Hash.optional
  end
end
