# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_role_management_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureRoleManagementPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_role_management_policy,
      attributes_class: Azure::Types::RoleManagementPolicyAttributes,
      outputs: { id: :id },
      map: [:role_definition_id, :scope],
      map_present: [:activation_rules, :active_assignment_rules, :eligible_assignment_rules, :notification_rules]
  end
  module Azure
    include AzureRoleManagementPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
