# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class ContainerRegistryAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :location, T::String
    attribute :name, T::String
    attribute :resource_group_name, T::String
    attribute :sku, T::String
    attribute? :admin_enabled, T::Bool.optional
    attribute? :anonymous_pull_enabled, T::Bool.optional
    attribute? :data_endpoint_enabled, T::Bool.optional
    attribute? :export_policy_enabled, T::Bool.optional
    attribute? :georeplications, T::Array.of(T::Hash).optional
    attribute? :identity, T::Array.of(T::Hash).optional
    attribute? :network_rule_bypass_option, T::String.optional
    attribute? :public_network_access_enabled, T::Bool.optional
    attribute? :quarantine_policy_enabled, T::Bool.optional
    attribute? :retention_policy_in_days, T::Float.optional
    attribute? :tags, T::Hash.optional
    attribute? :trust_policy_enabled, T::Bool.optional
    attribute? :zone_redundancy_enabled, T::Bool.optional
  end
end
