# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_resource_group_template_deployment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureResourceGroupTemplateDeployment
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_resource_group_template_deployment,
      attributes_class: Azure::Types::ResourceGroupTemplateDeploymentAttributes,
      outputs: { id: :id },
      map: [:deployment_mode, :name, :resource_group_name],
      map_present: [:debug_level, :parameters_content, :tags, :template_content, :template_spec_version_id]
  end
  module Azure
    include AzureResourceGroupTemplateDeployment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
