# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class SentinelDataConnectorMicrosoftCloudAppSecurityAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :log_analytics_workspace_id, T::String
    attribute :name, T::String
    attribute? :alerts_enabled, T::Bool.optional
    attribute? :discovery_logs_enabled, T::Bool.optional
  end
end
