# Code generated by pangea-forge.
# InSpec profile for verifying azurerm_dedicated_host_group infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AZURERM_TOKEN and AZURERM_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/azurerm_dedicated_host_group/ -t azurerm://

control 'azurerm_dedicated_host_group-exists' do
  impact 1.0
  title 'Manages a azurerm_dedicated_host_group resource'
  desc 'Verify that the azurerm_dedicated_host_group resource exists and has expected properties'

  describe azurerm_dedicated_host_group(name: attribute('id')) do
    it { should exist }
    its('location') { should_not be_nil }
    its('name') { should_not be_nil }
    its('platform_fault_domain_count') { should_not be_nil }
    its('resource_group_name') { should_not be_nil }
  end
end
