# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class AutomanageConfigurationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :location, T::String
    attribute :name, T::String
    attribute :resource_group_name, T::String
    attribute? :antimalware, T::Array.of(T::Hash).optional
    attribute? :automation_account_enabled, T::Bool.optional
    attribute? :azure_security_baseline, T::Array.of(T::Hash).optional
    attribute? :backup, T::Array.of(T::Hash).optional
    attribute? :boot_diagnostics_enabled, T::Bool.optional
    attribute? :defender_for_cloud_enabled, T::Bool.optional
    attribute? :guest_configuration_enabled, T::Bool.optional
    attribute? :log_analytics_enabled, T::Bool.optional
    attribute? :status_change_alert_enabled, T::Bool.optional
    attribute? :tags, T::Hash.optional
  end
end
