# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_backup_protected_file_share/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureBackupProtectedFileShare
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_backup_protected_file_share,
      attributes_class: Azure::Types::BackupProtectedFileShareAttributes,
      outputs: { id: :id },
      map: [:backup_policy_id, :recovery_vault_name, :resource_group_name, :source_file_share_name, :source_storage_account_id]
  end
  module Azure
    include AzureBackupProtectedFileShare
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
