# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class MonitorActionGroupAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Azure::Types

    attribute :name, T::String
    attribute :resource_group_name, T::String
    attribute :short_name, T::String
    attribute? :arm_role_receiver, T::Array.of(T::Hash).optional
    attribute? :automation_runbook_receiver, T::Array.of(T::Hash).optional
    attribute? :azure_app_push_receiver, T::Array.of(T::Hash).optional
    attribute? :azure_function_receiver, T::Array.of(T::Hash).optional
    attribute? :email_receiver, T::Array.of(T::Hash).optional
    attribute? :enabled, T::Bool.optional
    attribute? :event_hub_receiver, T::Array.of(T::Hash).optional
    attribute? :itsm_receiver, T::Array.of(T::Hash).optional
    attribute? :location, T::String.optional
    attribute? :logic_app_receiver, T::Array.of(T::Hash).optional
    attribute? :sms_receiver, T::Array.of(T::Hash).optional
    attribute? :tags, T::Hash.optional
    attribute? :voice_receiver, T::Array.of(T::Hash).optional
    attribute? :webhook_receiver, T::Array.of(T::Hash).optional
  end
end
