# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_postgresql_flexible_server_backup/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzurePostgresqlFlexibleServerBackup
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_postgresql_flexible_server_backup,
      attributes_class: Azure::Types::PostgresqlFlexibleServerBackupAttributes,
      outputs: { id: :id },
      map: [:name, :server_id]
  end
  module Azure
    include AzurePostgresqlFlexibleServerBackup
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
