# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class EventhubNamespaceSchemaGroupAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Azure::Types

    attribute :name, T::String
    attribute :namespace_id, T::String
    attribute :schema_compatibility, T::String
    attribute :schema_type, T::String
  end
end
