# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class DataFactoryIntegrationRuntimeAzureSsisAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :data_factory_id, T::String
    attribute :location, T::String
    attribute :name, T::String
    attribute :node_size, T::String
    attribute? :catalog_info, T::Array.of(T::Hash).optional
    attribute? :copy_compute_scale, T::Array.of(T::Hash).optional
    attribute? :credential_name, T::String.optional
    attribute? :custom_setup_script, T::Array.of(T::Hash).optional
    attribute? :description, T::String.optional
    attribute? :edition, T::String.optional
    attribute? :express_custom_setup, T::Array.of(T::Hash).optional
    attribute? :express_vnet_integration, T::Array.of(T::Hash).optional
    attribute? :license_type, T::String.optional
    attribute? :max_parallel_executions_per_node, T::Float.optional
    attribute? :number_of_nodes, T::Float.optional
    attribute? :package_store, T::Array.of(T::Hash).optional
    attribute? :pipeline_external_compute_scale, T::Array.of(T::Hash).optional
    attribute? :proxy, T::Array.of(T::Hash).optional
    attribute? :vnet_integration, T::Array.of(T::Hash).optional
  end
end
