# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_log_analytics_saved_search/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureLogAnalyticsSavedSearch
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_log_analytics_saved_search,
      attributes_class: Azure::Types::LogAnalyticsSavedSearchAttributes,
      outputs: { id: :id },
      map: [:category, :display_name, :log_analytics_workspace_id, :name, :query],
      map_present: [:function_alias, :function_parameters, :tags]
  end
  module Azure
    include AzureLogAnalyticsSavedSearch
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
