# Code generated by pangea-forge.
# InSpec profile for verifying azurerm_advisor_suppression infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AZURERM_TOKEN and AZURERM_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/azurerm_advisor_suppression/ -t azurerm://

control 'azurerm_advisor_suppression-exists' do
  impact 1.0
  title 'Manages a azurerm_advisor_suppression resource'
  desc 'Verify that the azurerm_advisor_suppression resource exists and has expected properties'

  describe azurerm_advisor_suppression(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
    its('recommendation_id') { should_not be_nil }
    its('resource_id') { should_not be_nil }
  end
end
