# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_sentinel_data_connector_iot/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureSentinelDataConnectorIot
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_sentinel_data_connector_iot,
      attributes_class: Azure::Types::SentinelDataConnectorIotAttributes,
      outputs: { id: :id },
      map: [:log_analytics_workspace_id, :name]
  end
  module Azure
    include AzureSentinelDataConnectorIot
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
