# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class CosmosdbMongoUserDefinitionAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :cosmos_mongo_database_id, T::String
    attribute :password, T::String
    attribute :username, T::String
    attribute? :inherited_role_names, T::Array.of(T::String).optional
  end
end
