# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class CognitiveAccountCustomerManagedKeyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :cognitive_account_id, T::String
    attribute :key_vault_key_id, T::String
    attribute? :identity_client_id, T::String.optional
  end
end
