# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_api_management_api/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureApiManagementApi
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_api_management_api,
      attributes_class: Azure::Types::ApiManagementApiAttributes,
      outputs: { id: :id },
      map: [:api_management_name, :name, :resource_group_name, :revision],
      map_present: [:api_type, :contact, :description, :display_name, :import, :license, :oauth2_authorization, :openid_authentication, :path, :protocols, :revision_description, :service_url, :source_api_id, :subscription_key_parameter_names, :terms_of_service_url, :version, :version_description, :version_set_id],
      map_bool: [:subscription_required]
  end
  module Azure
    include AzureApiManagementApi
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
