# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class NginxApiKeyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :end_date_time, T::String
    attribute :name, T::String
    attribute :nginx_deployment_id, T::String
    attribute :secret_text, T::String
  end
end
