# Code generated by pangea-forge.
# InSpec profile for verifying azurerm_dev_test_schedule infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AZURERM_TOKEN and AZURERM_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/azurerm_dev_test_schedule/ -t azurerm://

control 'azurerm_dev_test_schedule-exists' do
  impact 1.0
  title 'Manages a azurerm_dev_test_schedule resource'
  desc 'Verify that the azurerm_dev_test_schedule resource exists and has expected properties'

  describe azurerm_dev_test_schedule(name: attribute('id')) do
    it { should exist }
    its('lab_name') { should_not be_nil }
    its('location') { should_not be_nil }
    its('name') { should_not be_nil }
    its('notification_settings') { should_not be_nil }
    its('resource_group_name') { should_not be_nil }
    its('task_type') { should_not be_nil }
    its('time_zone_id') { should_not be_nil }
  end
end
