# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class ApiManagementWorkspaceCertificateAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :api_management_workspace_id, T::String
    attribute :name, T::String
    attribute? :certificate_data_base64, T::String.optional
    attribute? :key_vault_secret_id, T::String.optional
    attribute? :password, T::String.optional
    attribute? :user_assigned_identity_client_id, T::String.optional
  end
end
