# Code generated by pangea-forge.
# InSpec profile for verifying azurerm_ssh_public_key infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AZURERM_TOKEN and AZURERM_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/azurerm_ssh_public_key/ -t azurerm://

control 'azurerm_ssh_public_key-exists' do
  impact 1.0
  title 'Manages a azurerm_ssh_public_key resource'
  desc 'Verify that the azurerm_ssh_public_key resource exists and has expected properties'

  describe azurerm_ssh_public_key(name: attribute('id')) do
    it { should exist }
    its('location') { should_not be_nil }
    its('name') { should_not be_nil }
    its('public_key') { should_not be_nil }
    its('resource_group_name') { should_not be_nil }
  end
end
