# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class StreamAnalyticsOutputMssqlAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Azure::Types

    attribute :database, T::String
    attribute :name, T::String
    attribute :resource_group_name, T::String
    attribute :server, T::String
    attribute :stream_analytics_job_name, T::String
    attribute :table, T::String
    attribute? :authentication_mode, T::String.optional
    attribute? :max_batch_count, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :max_writer_count, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :password, T::String.optional
    attribute? :user, T::String.optional
  end
end
