# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class ContainerRegistryCredentialSetAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :authentication_credentials, T::Array.of(T::Hash)
    attribute :container_registry_id, T::String
    attribute :identity, T::Array.of(T::Hash)
    attribute :login_server, T::String
    attribute :name, T::String
  end
end
