# Code generated by pangea-forge.
# InSpec profile for verifying azurerm_dev_center_environment_type infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AZURERM_TOKEN and AZURERM_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/azurerm_dev_center_environment_type/ -t azurerm://

control 'azurerm_dev_center_environment_type-exists' do
  impact 1.0
  title 'Manages a azurerm_dev_center_environment_type resource'
  desc 'Verify that the azurerm_dev_center_environment_type resource exists and has expected properties'

  describe azurerm_dev_center_environment_type(name: attribute('id')) do
    it { should exist }
    its('dev_center_id') { should_not be_nil }
    its('name') { should_not be_nil }
  end
end
