# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class StorageSyncCloudEndpointAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :file_share_name, T::String
    attribute :name, T::String
    attribute :storage_account_id, T::String
    attribute :storage_sync_group_id, T::String
  end
end
