# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_subnet_route_table_association/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureSubnetRouteTableAssociation
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_subnet_route_table_association,
      attributes_class: Azure::Types::SubnetRouteTableAssociationAttributes,
      outputs: { id: :id },
      map: [:route_table_id, :subnet_id]
  end
  module Azure
    include AzureSubnetRouteTableAssociation
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
