# Code generated by pangea-forge.
# InSpec profile for verifying azurerm_databricks_access_connector infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AZURERM_TOKEN and AZURERM_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/azurerm_databricks_access_connector/ -t azurerm://

control 'azurerm_databricks_access_connector-exists' do
  impact 1.0
  title 'Manages a azurerm_databricks_access_connector resource'
  desc 'Verify that the azurerm_databricks_access_connector resource exists and has expected properties'

  describe azurerm_databricks_access_connector(name: attribute('id')) do
    it { should exist }
    its('location') { should_not be_nil }
    its('name') { should_not be_nil }
    its('resource_group_name') { should_not be_nil }
  end
end
