# Code generated by pangea-forge.
# InSpec profile for verifying azurerm_postgresql_server infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AZURERM_TOKEN and AZURERM_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/azurerm_postgresql_server/ -t azurerm://

control 'azurerm_postgresql_server-exists' do
  impact 1.0
  title 'Manages a azurerm_postgresql_server resource'
  desc 'Verify that the azurerm_postgresql_server resource exists and has expected properties'

  describe azurerm_postgresql_server(name: attribute('id')) do
    it { should exist }
    its('location') { should_not be_nil }
    its('name') { should_not be_nil }
    its('resource_group_name') { should_not be_nil }
    its('sku_name') { should_not be_nil }
    its('ssl_enforcement_enabled') { should_not be_nil }
    its('version') { should_not be_nil }
  end
end
