# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class LogicAppIntegrationAccountCertificateAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :integration_account_name, T::String
    attribute :name, T::String
    attribute :resource_group_name, T::String
    attribute? :key_vault_key, T::Array.of(T::Hash).optional
    attribute? :metadata, T::String.optional
    attribute? :public_certificate, T::String.optional
  end
end
