# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class EventgridNamespaceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :location, T::String
    attribute :name, T::String
    attribute :resource_group_name, T::String
    attribute? :capacity, T::Float.optional
    attribute? :identity, T::Array.of(T::Hash).optional
    attribute? :inbound_ip_rule, T::Array.of(T::Hash).optional
    attribute? :public_network_access, T::String.optional
    attribute? :sku, T::String.optional
    attribute? :tags, T::Hash.optional
    attribute? :topic_spaces_configuration, T::Array.of(T::Hash).optional
  end
end
