# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_mongo_cluster_user/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureMongoClusterUser
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_mongo_cluster_user,
      attributes_class: Azure::Types::MongoClusterUserAttributes,
      outputs: { id: :id },
      map: [:identity_provider_type, :mongo_cluster_id, :object_id, :principal_type, :role]
  end
  module Azure
    include AzureMongoClusterUser
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
