# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_signalr_shared_private_link_resource/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureSignalrSharedPrivateLinkResource
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_signalr_shared_private_link_resource,
      attributes_class: Azure::Types::SignalrSharedPrivateLinkResourceAttributes,
      outputs: { id: :id },
      map: [:name, :signalr_service_id, :sub_resource_name, :target_resource_id],
      map_present: [:request_message]
  end
  module Azure
    include AzureSignalrSharedPrivateLinkResource
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
