# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_firewall_network_rule_collection/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureFirewallNetworkRuleCollection
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_firewall_network_rule_collection,
      attributes_class: Azure::Types::FirewallNetworkRuleCollectionAttributes,
      outputs: { id: :id },
      map: [:action, :azure_firewall_name, :name, :priority, :resource_group_name, :rule]
  end
  module Azure
    include AzureFirewallNetworkRuleCollection
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
