# Code generated by pangea-forge.
# InSpec profile for verifying azurerm_api_management_identity_provider_aadb2c infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AZURERM_TOKEN and AZURERM_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/azurerm_api_management_identity_provider_aadb2c/ -t azurerm://

control 'azurerm_api_management_identity_provider_aadb2c-exists' do
  impact 1.0
  title 'Manages a azurerm_api_management_identity_provider_aadb2c resource'
  desc 'Verify that the azurerm_api_management_identity_provider_aadb2c resource exists and has expected properties'

  describe azurerm_api_management_identity_provider_aadb2c(name: attribute('id')) do
    it { should exist }
    its('allowed_tenant') { should_not be_nil }
    its('api_management_name') { should_not be_nil }
    its('authority') { should_not be_nil }
    its('client_id') { should_not be_nil }
    its('resource_group_name') { should_not be_nil }
    its('signin_policy') { should_not be_nil }
    its('signin_tenant') { should_not be_nil }
    its('signup_policy') { should_not be_nil }
  end
end
