# Code generated by pangea-forge.
# InSpec profile for verifying azurerm_notification_hub_namespace infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AZURERM_TOKEN and AZURERM_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/azurerm_notification_hub_namespace/ -t azurerm://

control 'azurerm_notification_hub_namespace-exists' do
  impact 1.0
  title 'Manages a azurerm_notification_hub_namespace resource'
  desc 'Verify that the azurerm_notification_hub_namespace resource exists and has expected properties'

  describe azurerm_notification_hub_namespace(name: attribute('id')) do
    it { should exist }
    its('location') { should_not be_nil }
    its('name') { should_not be_nil }
    its('namespace_type') { should_not be_nil }
    its('resource_group_name') { should_not be_nil }
    its('sku_name') { should_not be_nil }
  end
end
