# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class SpringCloudBuilderAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :build_pack_group, T::Array.of(T::Hash)
    attribute :name, T::String
    attribute :spring_cloud_service_id, T::String
    attribute :stack, T::Array.of(T::Hash)
  end
end
