# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class PrivateDnsResolverForwardingRuleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :dns_forwarding_ruleset_id, T::String
    attribute :domain_name, T::String
    attribute :name, T::String
    attribute :target_dns_servers, T::Array.of(T::Hash)
    attribute? :enabled, T::Bool.optional
    attribute? :metadata, T::Hash.optional
  end
end
