# Code generated by pangea-forge.
# InSpec profile for verifying azurerm_site_recovery_replicated_vm infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AZURERM_TOKEN and AZURERM_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/azurerm_site_recovery_replicated_vm/ -t azurerm://

control 'azurerm_site_recovery_replicated_vm-exists' do
  impact 1.0
  title 'Manages a azurerm_site_recovery_replicated_vm resource'
  desc 'Verify that the azurerm_site_recovery_replicated_vm resource exists and has expected properties'

  describe azurerm_site_recovery_replicated_vm(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
    its('recovery_replication_policy_id') { should_not be_nil }
    its('recovery_vault_name') { should_not be_nil }
    its('resource_group_name') { should_not be_nil }
    its('source_recovery_fabric_name') { should_not be_nil }
    its('source_recovery_protection_container_name') { should_not be_nil }
    its('source_vm_id') { should_not be_nil }
    its('target_recovery_fabric_id') { should_not be_nil }
    its('target_recovery_protection_container_id') { should_not be_nil }
    its('target_resource_group_id') { should_not be_nil }
  end
end
