# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_cdn_frontdoor_profile/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureCdnFrontdoorProfile
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_cdn_frontdoor_profile,
      attributes_class: Azure::Types::CdnFrontdoorProfileAttributes,
      outputs: { id: :id },
      map: [:name, :resource_group_name, :sku_name],
      map_present: [:identity, :log_scrubbing_rule, :response_timeout_seconds, :tags]
  end
  module Azure
    include AzureCdnFrontdoorProfile
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
