# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class NetappSnapshotPolicyAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Azure::Types

    attribute :account_name, T::String
    attribute :enabled, T::Bool
    attribute :location, T::String
    attribute :name, T::String
    attribute :resource_group_name, T::String
    attribute? :daily_schedule, T::Hash.optional
    attribute? :hourly_schedule, T::Hash.optional
    attribute? :monthly_schedule, T::Hash.optional
    attribute? :tags, T::Hash.optional
    attribute? :weekly_schedule, T::Hash.optional
  end
end
