# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class ApiManagementOpenidConnectProviderAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Azure::Types

    attribute :api_management_name, T::String
    attribute :client_id, T::String
    attribute :client_secret, T::String
    attribute :display_name, T::String
    attribute :metadata_endpoint, T::String
    attribute :name, T::String
    attribute :resource_group_name, T::String
    attribute? :description, T::String.optional
  end
end
