# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_maintenance_assignment_dynamic_scope/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureMaintenanceAssignmentDynamicScope
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_maintenance_assignment_dynamic_scope,
      attributes_class: Azure::Types::MaintenanceAssignmentDynamicScopeAttributes,
      outputs: { id: :id },
      map: [:filter, :maintenance_configuration_id, :name]
  end
  module Azure
    include AzureMaintenanceAssignmentDynamicScope
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
