# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class IothubFallbackRouteAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :enabled, T::Bool
    attribute :endpoint_names, T::Array.of(T::String)
    attribute :iothub_name, T::String
    attribute :resource_group_name, T::String
    attribute? :condition, T::String.optional
    attribute? :source, T::String.optional
  end
end
