# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_app_service_source_control_slot/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureAppServiceSourceControlSlot
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_app_service_source_control_slot,
      attributes_class: Azure::Types::AppServiceSourceControlSlotAttributes,
      outputs: { id: :id },
      map: [:slot_id],
      map_present: [:github_action_configuration],
      map_bool: [:rollback_enabled, :use_local_git, :use_manual_integration, :use_mercurial]
  end
  module Azure
    include AzureAppServiceSourceControlSlot
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
