# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class SentinelAutomationRuleAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Azure::Types

    attribute :display_name, T::String
    attribute :log_analytics_workspace_id, T::String
    attribute :name, T::String
    attribute :order, (T::Coercible::Integer | T::Coercible::Float)
    attribute? :action_incident, T::Array.of(T::Hash).optional
    attribute? :action_incident_task, T::Array.of(T::Hash).optional
    attribute? :action_playbook, T::Array.of(T::Hash).optional
    attribute? :condition_json, T::String.optional
    attribute? :enabled, T::Bool.optional
    attribute? :expiration, T::String.optional
    attribute? :triggers_on, T::String.optional
    attribute? :triggers_when, T::String.optional
  end
end
