# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class PaloAltoLocalRulestackFqdnListAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :fully_qualified_domain_names, T::Array.of(T::String)
    attribute :name, T::String
    attribute :rulestack_id, T::String
    attribute? :audit_comment, T::String.optional
    attribute? :description, T::String.optional
  end
end
