# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_machine_learning_workspace_network_outbound_rule_private_endpoint/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureMachineLearningWorkspaceNetworkOutboundRulePrivateEndpoint
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_machine_learning_workspace_network_outbound_rule_private_endpoint,
      attributes_class: Azure::Types::MachineLearningWorkspaceNetworkOutboundRulePrivateEndpointAttributes,
      outputs: { id: :id },
      map: [:name, :service_resource_id, :sub_resource_target, :workspace_id],
      map_bool: [:spark_enabled]
  end
  module Azure
    include AzureMachineLearningWorkspaceNetworkOutboundRulePrivateEndpoint
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
