# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class MssqlManagedInstanceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :license_type, T::String
    attribute :location, T::String
    attribute :name, T::String
    attribute :resource_group_name, T::String
    attribute :sku_name, T::String
    attribute :storage_size_in_gb, T::Float
    attribute :subnet_id, T::String
    attribute :vcores, T::Float
    attribute? :administrator_login_password, T::String.optional
    attribute? :azure_active_directory_administrator, T::Array.of(T::Hash).optional
    attribute? :collation, T::String.optional
    attribute? :database_format, T::String.optional
    attribute? :dns_zone_partner_id, T::String.optional
    attribute? :hybrid_secondary_usage, T::String.optional
    attribute? :identity, T::Array.of(T::Hash).optional
    attribute? :maintenance_configuration_name, T::String.optional
    attribute? :minimum_tls_version, T::String.optional
    attribute? :public_data_endpoint_enabled, T::Bool.optional
    attribute? :service_principal_type, T::String.optional
    attribute? :storage_account_type, T::String.optional
    attribute? :tags, T::Hash.optional
    attribute? :timezone_id, T::String.optional
    attribute? :zone_redundant_enabled, T::Bool.optional
  end
end
