# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class ApiManagementSubscriptionAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :api_management_name, T::String
    attribute :display_name, T::String
    attribute :resource_group_name, T::String
    attribute? :allow_tracing, T::Bool.optional
    attribute? :api_id, T::String.optional
    attribute? :product_id, T::String.optional
    attribute? :state, T::String.optional
    attribute? :user_id, T::String.optional
  end
end
