# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_monitor_scheduled_query_rules_log/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureMonitorScheduledQueryRulesLog
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_monitor_scheduled_query_rules_log,
      attributes_class: Azure::Types::MonitorScheduledQueryRulesLogAttributes,
      outputs: { id: :id },
      map: [:criteria, :data_source_id, :location, :name, :resource_group_name],
      map_present: [:authorized_resource_ids, :description, :tags],
      map_bool: [:enabled]
  end
  module Azure
    include AzureMonitorScheduledQueryRulesLog
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
