# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class PostgresqlFlexibleServerFirewallRuleAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Azure::Types

    attribute :end_ip_address, T::String
    attribute :name, T::String
    attribute :server_id, T::String
    attribute :start_ip_address, T::String
  end
end
