# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class Aadb2cDirectoryAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Azure::Types

    attribute :data_residency_location, T::String
    attribute :domain_name, T::String
    attribute :resource_group_name, T::String
    attribute :sku_name, T::String
    attribute? :country_code, T::String.optional
    attribute? :display_name, T::String.optional
    attribute? :tags, T::Hash.optional
  end
end
