# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class EventhubConsumerGroupAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :eventhub_name, T::String
    attribute :name, T::String
    attribute :namespace_name, T::String
    attribute :resource_group_name, T::String
    attribute? :user_metadata, T::String.optional
  end
end
