# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class DynatraceTagRulesAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :monitor_id, T::String
    attribute :name, T::String
    attribute? :log_rule, T::Array.of(T::Hash).optional
    attribute? :metric_rule, T::Array.of(T::Hash).optional
  end
end
