# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_firewall/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureFirewall
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_firewall,
      attributes_class: Azure::Types::FirewallAttributes,
      outputs: { id: :id },
      map: [:location, :name, :resource_group_name, :sku_name, :sku_tier],
      map_present: [:dns_servers, :firewall_policy_id, :ip_configuration, :management_ip_configuration, :private_ip_ranges, :tags, :threat_intel_mode, :virtual_hub, :zones],
      map_bool: [:dns_proxy_enabled]
  end
  module Azure
    include AzureFirewall
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
