# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_app_service_managed_certificate/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureAppServiceManagedCertificate
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_app_service_managed_certificate,
      attributes_class: Azure::Types::AppServiceManagedCertificateAttributes,
      outputs: { id: :id },
      map: [:custom_hostname_binding_id],
      map_present: [:tags]
  end
  module Azure
    include AzureAppServiceManagedCertificate
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
