# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class SystemCenterVirtualMachineManagerVirtualMachineInstanceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :custom_location_id, T::String
    attribute :infrastructure, T::Array.of(T::Hash)
    attribute :scoped_resource_id, T::String
    attribute? :hardware, T::Array.of(T::Hash).optional
    attribute? :network_interface, T::Array.of(T::Hash).optional
    attribute? :operating_system, T::Array.of(T::Hash).optional
    attribute? :storage_disk, T::Array.of(T::Hash).optional
    attribute? :system_center_virtual_machine_manager_availability_set_ids, T::Array.of(T::String).optional
  end
end
