# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class WorkloadsSapDiscoveryVirtualInstanceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :central_server_virtual_machine_id, T::String
    attribute :environment, T::String
    attribute :location, T::String
    attribute :name, T::String
    attribute :resource_group_name, T::String
    attribute :sap_product, T::String
    attribute? :identity, T::Array.of(T::Hash).optional
    attribute? :managed_resource_group_name, T::String.optional
    attribute? :managed_resources_network_access_type, T::String.optional
    attribute? :managed_storage_account_name, T::String.optional
    attribute? :tags, T::Hash.optional
  end
end
