# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_bot_channel_directline/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureBotChannelDirectline
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_bot_channel_directline,
      attributes_class: Azure::Types::BotChannelDirectlineAttributes,
      outputs: { id: :id },
      map: [:bot_name, :location, :resource_group_name, :site]
  end
  module Azure
    include AzureBotChannelDirectline
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
