# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_batch_pool/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureBatchPool
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_batch_pool,
      attributes_class: Azure::Types::BatchPoolAttributes,
      outputs: { id: :id },
      map: [:account_name, :name, :node_agent_sku_id, :resource_group_name, :storage_image_reference, :vm_size],
      map_present: [:auto_scale, :certificate, :container_configuration, :data_disks, :disk_encryption, :display_name, :extensions, :fixed_scale, :identity, :inter_node_communication, :license_type, :max_tasks_per_node, :metadata, :mount, :network_configuration, :node_placement, :os_disk_placement, :security_profile, :start_task, :target_node_communication_mode, :task_scheduling_policy, :user_accounts, :windows],
      map_bool: [:stop_pending_resize_operation]
  end
  module Azure
    include AzureBatchPool
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
