# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class DataProtectionBackupPolicyMysqlFlexibleServerAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :backup_repeating_time_intervals, T::Array.of(T::String)
    attribute :default_retention_rule, T::Array.of(T::Hash)
    attribute :name, T::String
    attribute :vault_id, T::String
    attribute? :retention_rule, T::Array.of(T::Hash).optional
    attribute? :time_zone, T::String.optional
  end
end
