# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_new_relic_tag_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureNewRelicTagRule
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_new_relic_tag_rule,
      attributes_class: Azure::Types::NewRelicTagRuleAttributes,
      outputs: { id: :id },
      map: [:monitor_id],
      map_present: [:log_tag_filter, :metric_tag_filter],
      map_bool: [:activity_log_enabled, :azure_active_directory_log_enabled, :metric_enabled, :subscription_log_enabled]
  end
  module Azure
    include AzureNewRelicTagRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
