# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_kusto_cosmosdb_data_connection/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureKustoCosmosdbDataConnection
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_kusto_cosmosdb_data_connection,
      attributes_class: Azure::Types::KustoCosmosdbDataConnectionAttributes,
      outputs: { id: :id },
      map: [:cosmosdb_container_id, :kusto_database_id, :location, :managed_identity_id, :name, :table_name],
      map_present: [:mapping_rule_name, :retrieval_start_date]
  end
  module Azure
    include AzureKustoCosmosdbDataConnection
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
