# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class MonitorWorkspaceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :location, T::String
    attribute :name, T::String
    attribute :resource_group_name, T::String
    attribute? :public_network_access_enabled, T::Bool.optional
    attribute? :tags, T::Hash.optional
  end
end
