# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class MaintenanceAssignmentVirtualMachineScaleSetAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Azure::Types

    attribute :location, T::String
    attribute :maintenance_configuration_id, T::String
    attribute :virtual_machine_scale_set_id, T::String
  end
end
