# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_sentinel_threat_intelligence_indicator/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureSentinelThreatIntelligenceIndicator
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_sentinel_threat_intelligence_indicator,
      attributes_class: Azure::Types::SentinelThreatIntelligenceIndicatorAttributes,
      outputs: { id: :id },
      map: [:display_name, :pattern, :pattern_type, :source, :validate_from_utc, :workspace_id],
      map_present: [:confidence, :created_by, :description, :external_reference, :granular_marking, :kill_chain_phase, :language, :object_marking_refs, :pattern_version, :tags, :threat_types, :validate_until_utc],
      map_bool: [:revoked]
  end
  module Azure
    include AzureSentinelThreatIntelligenceIndicator
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
