# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_virtual_desktop_scaling_plan_host_pool_association/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureVirtualDesktopScalingPlanHostPoolAssociation
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_virtual_desktop_scaling_plan_host_pool_association,
      attributes_class: Azure::Types::VirtualDesktopScalingPlanHostPoolAssociationAttributes,
      outputs: { id: :id },
      map: [:host_pool_id, :scaling_plan_id],
      map_bool: [:enabled]
  end
  module Azure
    include AzureVirtualDesktopScalingPlanHostPoolAssociation
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
