# Code generated by pangea-forge.
# InSpec profile for verifying azurerm_servicebus_subscription infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AZURERM_TOKEN and AZURERM_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/azurerm_servicebus_subscription/ -t azurerm://

control 'azurerm_servicebus_subscription-exists' do
  impact 1.0
  title 'Manages a azurerm_servicebus_subscription resource'
  desc 'Verify that the azurerm_servicebus_subscription resource exists and has expected properties'

  describe azurerm_servicebus_subscription(name: attribute('id')) do
    it { should exist }
    its('max_delivery_count') { should_not be_nil }
    its('name') { should_not be_nil }
    its('topic_id') { should_not be_nil }
  end
end
