# Code generated by pangea-forge.
# InSpec profile for verifying azurerm_eventhub_namespace_customer_managed_key infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AZURERM_TOKEN and AZURERM_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/azurerm_eventhub_namespace_customer_managed_key/ -t azurerm://

control 'azurerm_eventhub_namespace_customer_managed_key-exists' do
  impact 1.0
  title 'Manages a azurerm_eventhub_namespace_customer_managed_key resource'
  desc 'Verify that the azurerm_eventhub_namespace_customer_managed_key resource exists and has expected properties'

  describe azurerm_eventhub_namespace_customer_managed_key(name: attribute('id')) do
    it { should exist }
    its('eventhub_namespace_id') { should_not be_nil }
    its('key_vault_key_ids') { should_not be_nil }
  end
end
