# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class AppServiceEnvironmentV3Attributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Azure::Types

    attribute :name, T::String
    attribute :resource_group_name, T::String
    attribute :subnet_id, T::String
    attribute? :allow_new_private_endpoint_connections, T::Bool.optional
    attribute? :cluster_setting, T::Array.of(T::Hash).optional
    attribute? :dedicated_host_count, T::Float.optional
    attribute? :internal_load_balancing_mode, T::String.optional
    attribute? :remote_debugging_enabled, T::Bool.optional
    attribute? :tags, T::Hash.optional
    attribute? :zone_redundant, T::Bool.optional
  end
end
