# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_key_vault_managed_hardware_security_module_role_definition/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureKeyVaultManagedHardwareSecurityModuleRoleDefinition
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_key_vault_managed_hardware_security_module_role_definition,
      attributes_class: Azure::Types::KeyVaultManagedHardwareSecurityModuleRoleDefinitionAttributes,
      outputs: { id: :id },
      map: [:managed_hsm_id, :name],
      map_present: [:description, :permission, :role_name]
  end
  module Azure
    include AzureKeyVaultManagedHardwareSecurityModuleRoleDefinition
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
