# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Azure::Types
  include Dry.Types()

  class IothubDeviceUpdateInstanceAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Azure::Types

    attribute :device_update_account_id, T::String
    attribute :iothub_id, T::String
    attribute :name, T::String
    attribute? :diagnostic_enabled, T::Bool.optional
    attribute? :diagnostic_storage_account, T::Hash.optional
    attribute? :tags, T::Hash.optional
  end
end
