# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/azurerm_data_factory_integration_runtime_self_hosted/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AzureDataFactoryIntegrationRuntimeSelfHosted
    include Pangea::Resources::ResourceBuilder

    define_resource :azurerm_data_factory_integration_runtime_self_hosted,
      attributes_class: Azure::Types::DataFactoryIntegrationRuntimeSelfHostedAttributes,
      outputs: { id: :id },
      map: [:data_factory_id, :name],
      map_present: [:description, :rbac_authorization],
      map_bool: [:self_contained_interactive_authoring_enabled]
  end
  module Azure
    include AzureDataFactoryIntegrationRuntimeSelfHosted
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Azure)
