# Code generated by pangea-forge.
# InSpec profile for verifying azurerm_resource_management_private_link_association infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AZURERM_TOKEN and AZURERM_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/azurerm_resource_management_private_link_association/ -t azurerm://

control 'azurerm_resource_management_private_link_association-exists' do
  impact 1.0
  title 'Manages a azurerm_resource_management_private_link_association resource'
  desc 'Verify that the azurerm_resource_management_private_link_association resource exists and has expected properties'

  describe azurerm_resource_management_private_link_association(name: attribute('id')) do
    it { should exist }
    its('management_group_id') { should_not be_nil }
    its('public_network_access_enabled') { should_not be_nil }
    its('resource_management_private_link_id') { should_not be_nil }
  end
end
