# Code generated by pangea-forge.
# InSpec profile for verifying azurerm_qumulo_file_system infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AZURERM_TOKEN and AZURERM_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/azurerm_qumulo_file_system/ -t azurerm://

control 'azurerm_qumulo_file_system-exists' do
  impact 1.0
  title 'Manages a azurerm_qumulo_file_system resource'
  desc 'Verify that the azurerm_qumulo_file_system resource exists and has expected properties'

  describe azurerm_qumulo_file_system(name: attribute('id')) do
    it { should exist }
    its('email') { should_not be_nil }
    its('location') { should_not be_nil }
    its('name') { should_not be_nil }
    its('resource_group_name') { should_not be_nil }
    its('storage_sku') { should_not be_nil }
    its('subnet_id') { should_not be_nil }
    its('zone') { should_not be_nil }
  end
end
