# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_cdn_frontdoor_rule resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureCdnFrontdoorRule do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { actions: { 'key1' => 'val1' }, cdn_frontdoor_rule_set_id: 'test-value', name: 'test-value', order: 3.14 } }

  describe ':azurerm_cdn_frontdoor_rule' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_cdn_frontdoor_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_cdn_frontdoor_rule', 'test')
        validate_required_attributes(config, [:actions, :cdn_frontdoor_rule_set_id, :name, :order])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_cdn_frontdoor_rule('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_cdn_frontdoor_rule)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_cdn_frontdoor_rule('test', required_attrs)

        expect(ref.id).to eq("${azurerm_cdn_frontdoor_rule.test.id}")
        expect(ref.cdn_frontdoor_rule_set_name).to eq("${azurerm_cdn_frontdoor_rule.test.cdn_frontdoor_rule_set_name}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_cdn_frontdoor_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_cdn_frontdoor_rule', 'test')
        expect(config).not_to have_key('cdn_frontdoor_rule_set_name')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ behavior_on_match: 'test-value', conditions: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_cdn_frontdoor_rule('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_cdn_frontdoor_rule', 'full')
        expect(config).to have_key('behavior_on_match')
        expect(config).to have_key('conditions')
      end
    end

    context 'optional attributes' do
      it 'includes behavior_on_match when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_cdn_frontdoor_rule('opt', required_attrs.merge(behavior_on_match: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_cdn_frontdoor_rule', 'opt')
        expect(config).to have_key('behavior_on_match')
      end

      it 'omits behavior_on_match when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_cdn_frontdoor_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_cdn_frontdoor_rule', 'minimal')
        expect(config).not_to have_key('behavior_on_match')
      end
      it 'includes conditions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_cdn_frontdoor_rule('opt', required_attrs.merge(conditions: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_cdn_frontdoor_rule', 'opt')
        expect(config).to have_key('conditions')
      end

      it 'omits conditions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_cdn_frontdoor_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_cdn_frontdoor_rule', 'minimal')
        expect(config).not_to have_key('conditions')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_cdn_frontdoor_rule('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_cdn_frontdoor_rule', 'typed')
        expect(config['actions']).to be_a(Hash)
        expect(config['cdn_frontdoor_rule_set_id']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['order']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_cdn_frontdoor_rule('first', required_attrs)
        synth.azurerm_cdn_frontdoor_rule('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_cdn_frontdoor_rule')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_cdn_frontdoor_rule,
    method: :azurerm_cdn_frontdoor_rule,
    required_attrs: { actions: { 'key1' => 'val1' }, cdn_frontdoor_rule_set_id: 'test-value', name: 'test-value', order: 3.14 },
    expected_outputs: [:id, :cdn_frontdoor_rule_set_name],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
