# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_frontdoor_firewall_policy resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureFrontdoorFirewallPolicy do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', resource_group_name: 'test-value' } }

  describe ':azurerm_frontdoor_firewall_policy' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_frontdoor_firewall_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_frontdoor_firewall_policy', 'test')
        validate_required_attributes(config, [:name, :resource_group_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_frontdoor_firewall_policy('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_frontdoor_firewall_policy)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_frontdoor_firewall_policy('test', required_attrs)

        expect(ref.id).to eq("${azurerm_frontdoor_firewall_policy.test.id}")
        expect(ref.frontend_endpoint_ids).to eq("${azurerm_frontdoor_firewall_policy.test.frontend_endpoint_ids}")
        expect(ref.location).to eq("${azurerm_frontdoor_firewall_policy.test.location}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_frontdoor_firewall_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_frontdoor_firewall_policy', 'test')
        expect(config).not_to have_key('frontend_endpoint_ids')
        expect(config).not_to have_key('location')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ custom_block_response_body: 'test-value', custom_block_response_status_code: 3.14, custom_rule: [{ 'key1' => 'val1' }], enabled: true, managed_rule: [{ 'key1' => 'val1' }], mode: 'test-value', redirect_url: 'test-value', tags: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_frontdoor_firewall_policy('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_frontdoor_firewall_policy', 'full')
        expect(config).to have_key('custom_block_response_body')
        expect(config).to have_key('custom_block_response_status_code')
        expect(config).to have_key('custom_rule')
        expect(config).to have_key('enabled')
        expect(config).to have_key('managed_rule')
        expect(config).to have_key('mode')
        expect(config).to have_key('redirect_url')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes custom_block_response_body when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_frontdoor_firewall_policy('opt', required_attrs.merge(custom_block_response_body: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_frontdoor_firewall_policy', 'opt')
        expect(config).to have_key('custom_block_response_body')
      end

      it 'omits custom_block_response_body when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_frontdoor_firewall_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_frontdoor_firewall_policy', 'minimal')
        expect(config).not_to have_key('custom_block_response_body')
      end
      it 'includes custom_block_response_status_code when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_frontdoor_firewall_policy('opt', required_attrs.merge(custom_block_response_status_code: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_frontdoor_firewall_policy', 'opt')
        expect(config).to have_key('custom_block_response_status_code')
      end

      it 'omits custom_block_response_status_code when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_frontdoor_firewall_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_frontdoor_firewall_policy', 'minimal')
        expect(config).not_to have_key('custom_block_response_status_code')
      end
      it 'includes custom_rule when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_frontdoor_firewall_policy('opt', required_attrs.merge(custom_rule: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_frontdoor_firewall_policy', 'opt')
        expect(config).to have_key('custom_rule')
      end

      it 'omits custom_rule when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_frontdoor_firewall_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_frontdoor_firewall_policy', 'minimal')
        expect(config).not_to have_key('custom_rule')
      end
      it 'includes enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_frontdoor_firewall_policy('opt', required_attrs.merge(enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_frontdoor_firewall_policy', 'opt')
        expect(config).to have_key('enabled')
      end

      it 'omits enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_frontdoor_firewall_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_frontdoor_firewall_policy', 'minimal')
        expect(config).not_to have_key('enabled')
      end
      it 'includes managed_rule when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_frontdoor_firewall_policy('opt', required_attrs.merge(managed_rule: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_frontdoor_firewall_policy', 'opt')
        expect(config).to have_key('managed_rule')
      end

      it 'omits managed_rule when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_frontdoor_firewall_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_frontdoor_firewall_policy', 'minimal')
        expect(config).not_to have_key('managed_rule')
      end
      it 'includes mode when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_frontdoor_firewall_policy('opt', required_attrs.merge(mode: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_frontdoor_firewall_policy', 'opt')
        expect(config).to have_key('mode')
      end

      it 'omits mode when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_frontdoor_firewall_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_frontdoor_firewall_policy', 'minimal')
        expect(config).not_to have_key('mode')
      end
      it 'includes redirect_url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_frontdoor_firewall_policy('opt', required_attrs.merge(redirect_url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_frontdoor_firewall_policy', 'opt')
        expect(config).to have_key('redirect_url')
      end

      it 'omits redirect_url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_frontdoor_firewall_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_frontdoor_firewall_policy', 'minimal')
        expect(config).not_to have_key('redirect_url')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_frontdoor_firewall_policy('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_frontdoor_firewall_policy', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_frontdoor_firewall_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_frontdoor_firewall_policy', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.azurerm_frontdoor_firewall_policy("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'azurerm_frontdoor_firewall_policy', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_frontdoor_firewall_policy('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_frontdoor_firewall_policy', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['resource_group_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_frontdoor_firewall_policy('first', required_attrs)
        synth.azurerm_frontdoor_firewall_policy('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_frontdoor_firewall_policy')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_frontdoor_firewall_policy,
    method: :azurerm_frontdoor_firewall_policy,
    required_attrs: { name: 'test-value', resource_group_name: 'test-value' },
    expected_outputs: [:id, :frontend_endpoint_ids, :location],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enabled]
end
