# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_service_fabric_cluster resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureServiceFabricCluster do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { location: 'test-value', management_endpoint: 'test-value', name: 'test-value', node_type: [{ 'key1' => 'val1' }], reliability_level: 'test-value', resource_group_name: 'test-value', upgrade_mode: 'test-value', vm_image: 'test-value' } }

  describe ':azurerm_service_fabric_cluster' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'test')
        validate_required_attributes(config, [:location, :management_endpoint, :name, :node_type, :reliability_level, :resource_group_name, :upgrade_mode, :vm_image])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_service_fabric_cluster('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_service_fabric_cluster)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_service_fabric_cluster('test', required_attrs)

        expect(ref.id).to eq("${azurerm_service_fabric_cluster.test.id}")
        expect(ref.cluster_code_version).to eq("${azurerm_service_fabric_cluster.test.cluster_code_version}")
        expect(ref.cluster_endpoint).to eq("${azurerm_service_fabric_cluster.test.cluster_endpoint}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'test')
        expect(config).not_to have_key('cluster_code_version')
        expect(config).not_to have_key('cluster_endpoint')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ add_on_features: ['test-value'], azure_active_directory: { 'key1' => 'val1' }, certificate: { 'key1' => 'val1' }, certificate_common_names: { 'key1' => 'val1' }, client_certificate_common_name: [{ 'key1' => 'val1' }], client_certificate_thumbprint: [{ 'key1' => 'val1' }], cluster_code_version: 'test-value', diagnostics_config: { 'key1' => 'val1' }, fabric_settings: [{ 'key1' => 'val1' }], reverse_proxy_certificate: { 'key1' => 'val1' }, reverse_proxy_certificate_common_names: { 'key1' => 'val1' }, service_fabric_zonal_upgrade_mode: 'test-value', tags: { 'key1' => 'val1' }, upgrade_policy: { 'key1' => 'val1' }, vmss_zonal_upgrade_mode: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'full')
        expect(config).to have_key('add_on_features')
        expect(config).to have_key('azure_active_directory')
        expect(config).to have_key('certificate')
        expect(config).to have_key('certificate_common_names')
        expect(config).to have_key('client_certificate_common_name')
        expect(config).to have_key('client_certificate_thumbprint')
        expect(config).to have_key('cluster_code_version')
        expect(config).to have_key('diagnostics_config')
        expect(config).to have_key('fabric_settings')
        expect(config).to have_key('reverse_proxy_certificate')
        expect(config).to have_key('reverse_proxy_certificate_common_names')
        expect(config).to have_key('service_fabric_zonal_upgrade_mode')
        expect(config).to have_key('tags')
        expect(config).to have_key('upgrade_policy')
        expect(config).to have_key('vmss_zonal_upgrade_mode')
      end
    end

    context 'optional attributes' do
      it 'includes add_on_features when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('opt', required_attrs.merge(add_on_features: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'opt')
        expect(config).to have_key('add_on_features')
      end

      it 'omits add_on_features when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'minimal')
        expect(config).not_to have_key('add_on_features')
      end
      it 'includes azure_active_directory when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('opt', required_attrs.merge(azure_active_directory: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'opt')
        expect(config).to have_key('azure_active_directory')
      end

      it 'omits azure_active_directory when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'minimal')
        expect(config).not_to have_key('azure_active_directory')
      end
      it 'includes certificate when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('opt', required_attrs.merge(certificate: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'opt')
        expect(config).to have_key('certificate')
      end

      it 'omits certificate when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'minimal')
        expect(config).not_to have_key('certificate')
      end
      it 'includes certificate_common_names when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('opt', required_attrs.merge(certificate_common_names: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'opt')
        expect(config).to have_key('certificate_common_names')
      end

      it 'omits certificate_common_names when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'minimal')
        expect(config).not_to have_key('certificate_common_names')
      end
      it 'includes client_certificate_common_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('opt', required_attrs.merge(client_certificate_common_name: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'opt')
        expect(config).to have_key('client_certificate_common_name')
      end

      it 'omits client_certificate_common_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'minimal')
        expect(config).not_to have_key('client_certificate_common_name')
      end
      it 'includes client_certificate_thumbprint when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('opt', required_attrs.merge(client_certificate_thumbprint: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'opt')
        expect(config).to have_key('client_certificate_thumbprint')
      end

      it 'omits client_certificate_thumbprint when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'minimal')
        expect(config).not_to have_key('client_certificate_thumbprint')
      end
      it 'includes cluster_code_version when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('opt', required_attrs.merge(cluster_code_version: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'opt')
        expect(config).to have_key('cluster_code_version')
      end

      it 'omits cluster_code_version when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'minimal')
        expect(config).not_to have_key('cluster_code_version')
      end
      it 'includes diagnostics_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('opt', required_attrs.merge(diagnostics_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'opt')
        expect(config).to have_key('diagnostics_config')
      end

      it 'omits diagnostics_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'minimal')
        expect(config).not_to have_key('diagnostics_config')
      end
      it 'includes fabric_settings when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('opt', required_attrs.merge(fabric_settings: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'opt')
        expect(config).to have_key('fabric_settings')
      end

      it 'omits fabric_settings when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'minimal')
        expect(config).not_to have_key('fabric_settings')
      end
      it 'includes reverse_proxy_certificate when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('opt', required_attrs.merge(reverse_proxy_certificate: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'opt')
        expect(config).to have_key('reverse_proxy_certificate')
      end

      it 'omits reverse_proxy_certificate when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'minimal')
        expect(config).not_to have_key('reverse_proxy_certificate')
      end
      it 'includes reverse_proxy_certificate_common_names when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('opt', required_attrs.merge(reverse_proxy_certificate_common_names: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'opt')
        expect(config).to have_key('reverse_proxy_certificate_common_names')
      end

      it 'omits reverse_proxy_certificate_common_names when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'minimal')
        expect(config).not_to have_key('reverse_proxy_certificate_common_names')
      end
      it 'includes service_fabric_zonal_upgrade_mode when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('opt', required_attrs.merge(service_fabric_zonal_upgrade_mode: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'opt')
        expect(config).to have_key('service_fabric_zonal_upgrade_mode')
      end

      it 'omits service_fabric_zonal_upgrade_mode when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'minimal')
        expect(config).not_to have_key('service_fabric_zonal_upgrade_mode')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes upgrade_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('opt', required_attrs.merge(upgrade_policy: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'opt')
        expect(config).to have_key('upgrade_policy')
      end

      it 'omits upgrade_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'minimal')
        expect(config).not_to have_key('upgrade_policy')
      end
      it 'includes vmss_zonal_upgrade_mode when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('opt', required_attrs.merge(vmss_zonal_upgrade_mode: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'opt')
        expect(config).to have_key('vmss_zonal_upgrade_mode')
      end

      it 'omits vmss_zonal_upgrade_mode when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'minimal')
        expect(config).not_to have_key('vmss_zonal_upgrade_mode')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_service_fabric_cluster', 'typed')
        expect(config['location']).to be_a(String)
        expect(config['management_endpoint']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['node_type']).to be_a(Array)
        expect(config['reliability_level']).to be_a(String)
        expect(config['resource_group_name']).to be_a(String)
        expect(config['upgrade_mode']).to be_a(String)
        expect(config['vm_image']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_service_fabric_cluster('first', required_attrs)
        synth.azurerm_service_fabric_cluster('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_service_fabric_cluster')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_service_fabric_cluster,
    method: :azurerm_service_fabric_cluster,
    required_attrs: { location: 'test-value', management_endpoint: 'test-value', name: 'test-value', node_type: [{ 'key1' => 'val1' }], reliability_level: 'test-value', resource_group_name: 'test-value', upgrade_mode: 'test-value', vm_image: 'test-value' },
    expected_outputs: [:id, :cluster_code_version, :cluster_endpoint],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
