# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_spring_cloud_storage resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureSpringCloudStorage do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', spring_cloud_service_id: 'test-value', storage_account_key: 'test-value', storage_account_name: 'test-value' } }

  describe ':azurerm_spring_cloud_storage' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_storage('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_storage', 'test')
        validate_required_attributes(config, [:name, :spring_cloud_service_id, :storage_account_key, :storage_account_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_spring_cloud_storage('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_spring_cloud_storage)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_spring_cloud_storage('test', required_attrs)

        expect(ref.id).to eq("${azurerm_spring_cloud_storage.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_storage('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_spring_cloud_storage', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['spring_cloud_service_id']).to be_a(String)
        expect(config['storage_account_key']).to be_a(String)
        expect(config['storage_account_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_storage('first', required_attrs)
        synth.azurerm_spring_cloud_storage('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_spring_cloud_storage')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_spring_cloud_storage,
    method: :azurerm_spring_cloud_storage,
    required_attrs: { name: 'test-value', spring_cloud_service_id: 'test-value', storage_account_key: 'test-value', storage_account_name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
