# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_container_connected_registry resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureContainerConnectedRegistry do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { container_registry_id: 'test-value', name: 'test-value', sync_token_id: 'test-value' } }

  describe ':azurerm_container_connected_registry' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_container_connected_registry('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_container_connected_registry', 'test')
        validate_required_attributes(config, [:container_registry_id, :name, :sync_token_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_container_connected_registry('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_container_connected_registry)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_container_connected_registry('test', required_attrs)

        expect(ref.id).to eq("${azurerm_container_connected_registry.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ audit_log_enabled: true, client_token_ids: ['test-value'], log_level: 'test-value', mode: 'test-value', notification: [{ 'key1' => 'val1' }], parent_registry_id: 'test-value', sync_message_ttl: 'test-value', sync_schedule: 'test-value', sync_window: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_container_connected_registry('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_container_connected_registry', 'full')
        expect(config).to have_key('audit_log_enabled')
        expect(config).to have_key('client_token_ids')
        expect(config).to have_key('log_level')
        expect(config).to have_key('mode')
        expect(config).to have_key('notification')
        expect(config).to have_key('parent_registry_id')
        expect(config).to have_key('sync_message_ttl')
        expect(config).to have_key('sync_schedule')
        expect(config).to have_key('sync_window')
      end
    end

    context 'optional attributes' do
      it 'includes audit_log_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_container_connected_registry('opt', required_attrs.merge(audit_log_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_container_connected_registry', 'opt')
        expect(config).to have_key('audit_log_enabled')
      end

      it 'omits audit_log_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_container_connected_registry('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_container_connected_registry', 'minimal')
        expect(config).not_to have_key('audit_log_enabled')
      end
      it 'includes client_token_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_container_connected_registry('opt', required_attrs.merge(client_token_ids: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_container_connected_registry', 'opt')
        expect(config).to have_key('client_token_ids')
      end

      it 'omits client_token_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_container_connected_registry('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_container_connected_registry', 'minimal')
        expect(config).not_to have_key('client_token_ids')
      end
      it 'includes log_level when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_container_connected_registry('opt', required_attrs.merge(log_level: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_container_connected_registry', 'opt')
        expect(config).to have_key('log_level')
      end

      it 'omits log_level when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_container_connected_registry('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_container_connected_registry', 'minimal')
        expect(config).not_to have_key('log_level')
      end
      it 'includes mode when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_container_connected_registry('opt', required_attrs.merge(mode: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_container_connected_registry', 'opt')
        expect(config).to have_key('mode')
      end

      it 'omits mode when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_container_connected_registry('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_container_connected_registry', 'minimal')
        expect(config).not_to have_key('mode')
      end
      it 'includes notification when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_container_connected_registry('opt', required_attrs.merge(notification: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_container_connected_registry', 'opt')
        expect(config).to have_key('notification')
      end

      it 'omits notification when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_container_connected_registry('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_container_connected_registry', 'minimal')
        expect(config).not_to have_key('notification')
      end
      it 'includes parent_registry_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_container_connected_registry('opt', required_attrs.merge(parent_registry_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_container_connected_registry', 'opt')
        expect(config).to have_key('parent_registry_id')
      end

      it 'omits parent_registry_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_container_connected_registry('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_container_connected_registry', 'minimal')
        expect(config).not_to have_key('parent_registry_id')
      end
      it 'includes sync_message_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_container_connected_registry('opt', required_attrs.merge(sync_message_ttl: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_container_connected_registry', 'opt')
        expect(config).to have_key('sync_message_ttl')
      end

      it 'omits sync_message_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_container_connected_registry('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_container_connected_registry', 'minimal')
        expect(config).not_to have_key('sync_message_ttl')
      end
      it 'includes sync_schedule when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_container_connected_registry('opt', required_attrs.merge(sync_schedule: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_container_connected_registry', 'opt')
        expect(config).to have_key('sync_schedule')
      end

      it 'omits sync_schedule when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_container_connected_registry('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_container_connected_registry', 'minimal')
        expect(config).not_to have_key('sync_schedule')
      end
      it 'includes sync_window when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_container_connected_registry('opt', required_attrs.merge(sync_window: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_container_connected_registry', 'opt')
        expect(config).to have_key('sync_window')
      end

      it 'omits sync_window when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_container_connected_registry('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_container_connected_registry', 'minimal')
        expect(config).not_to have_key('sync_window')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts audit_log_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(audit_log_enabled: val)
          synth.azurerm_container_connected_registry("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'azurerm_container_connected_registry', "bool_#{val}")
          expect(config['audit_log_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_container_connected_registry('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_container_connected_registry', 'typed')
        expect(config['container_registry_id']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['sync_token_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_container_connected_registry('first', required_attrs)
        synth.azurerm_container_connected_registry('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_container_connected_registry')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_container_connected_registry,
    method: :azurerm_container_connected_registry,
    required_attrs: { container_registry_id: 'test-value', name: 'test-value', sync_token_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:audit_log_enabled]
end
