# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_batch_account resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureBatchAccount do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { location: 'test-value', name: 'test-value', resource_group_name: 'test-value' } }

  describe ':azurerm_batch_account' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'test')
        validate_required_attributes(config, [:location, :name, :resource_group_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_batch_account('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_batch_account)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_batch_account('test', required_attrs)

        expect(ref.id).to eq("${azurerm_batch_account.test.id}")
        expect(ref.account_endpoint).to eq("${azurerm_batch_account.test.account_endpoint}")
        expect(ref.allowed_authentication_modes).to eq("${azurerm_batch_account.test.allowed_authentication_modes}")
        expect(ref.primary_access_key).to eq("${azurerm_batch_account.test.primary_access_key}")
        expect(ref.secondary_access_key).to eq("${azurerm_batch_account.test.secondary_access_key}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_batch_account', 'test')
        expect(config).not_to have_key('account_endpoint')
        expect(config).not_to have_key('allowed_authentication_modes')
        expect(config).not_to have_key('primary_access_key')
        expect(config).not_to have_key('secondary_access_key')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allowed_authentication_modes: ['test-value'], encryption: [{ 'key1' => 'val1' }], identity: { 'key1' => 'val1' }, key_vault_reference: { 'key1' => 'val1' }, network_profile: { 'key1' => 'val1' }, pool_allocation_mode: 'test-value', public_network_access_enabled: true, storage_account_authentication_mode: 'test-value', storage_account_id: 'test-value', storage_account_node_identity: 'test-value', tags: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_batch_account', 'full')
        expect(config).to have_key('allowed_authentication_modes')
        expect(config).to have_key('encryption')
        expect(config).to have_key('identity')
        expect(config).to have_key('key_vault_reference')
        expect(config).to have_key('network_profile')
        expect(config).to have_key('pool_allocation_mode')
        expect(config).to have_key('public_network_access_enabled')
        expect(config).to have_key('storage_account_authentication_mode')
        expect(config).to have_key('storage_account_id')
        expect(config).to have_key('storage_account_node_identity')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes allowed_authentication_modes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('opt', required_attrs.merge(allowed_authentication_modes: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'opt')
        expect(config).to have_key('allowed_authentication_modes')
      end

      it 'omits allowed_authentication_modes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'minimal')
        expect(config).not_to have_key('allowed_authentication_modes')
      end
      it 'includes encryption when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('opt', required_attrs.merge(encryption: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'opt')
        expect(config).to have_key('encryption')
      end

      it 'omits encryption when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'minimal')
        expect(config).not_to have_key('encryption')
      end
      it 'includes identity when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('opt', required_attrs.merge(identity: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'opt')
        expect(config).to have_key('identity')
      end

      it 'omits identity when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'minimal')
        expect(config).not_to have_key('identity')
      end
      it 'includes key_vault_reference when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('opt', required_attrs.merge(key_vault_reference: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'opt')
        expect(config).to have_key('key_vault_reference')
      end

      it 'omits key_vault_reference when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'minimal')
        expect(config).not_to have_key('key_vault_reference')
      end
      it 'includes network_profile when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('opt', required_attrs.merge(network_profile: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'opt')
        expect(config).to have_key('network_profile')
      end

      it 'omits network_profile when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'minimal')
        expect(config).not_to have_key('network_profile')
      end
      it 'includes pool_allocation_mode when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('opt', required_attrs.merge(pool_allocation_mode: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'opt')
        expect(config).to have_key('pool_allocation_mode')
      end

      it 'omits pool_allocation_mode when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'minimal')
        expect(config).not_to have_key('pool_allocation_mode')
      end
      it 'includes public_network_access_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('opt', required_attrs.merge(public_network_access_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'opt')
        expect(config).to have_key('public_network_access_enabled')
      end

      it 'omits public_network_access_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'minimal')
        expect(config).not_to have_key('public_network_access_enabled')
      end
      it 'includes storage_account_authentication_mode when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('opt', required_attrs.merge(storage_account_authentication_mode: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'opt')
        expect(config).to have_key('storage_account_authentication_mode')
      end

      it 'omits storage_account_authentication_mode when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'minimal')
        expect(config).not_to have_key('storage_account_authentication_mode')
      end
      it 'includes storage_account_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('opt', required_attrs.merge(storage_account_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'opt')
        expect(config).to have_key('storage_account_id')
      end

      it 'omits storage_account_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'minimal')
        expect(config).not_to have_key('storage_account_id')
      end
      it 'includes storage_account_node_identity when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('opt', required_attrs.merge(storage_account_node_identity: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'opt')
        expect(config).to have_key('storage_account_node_identity')
      end

      it 'omits storage_account_node_identity when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'minimal')
        expect(config).not_to have_key('storage_account_node_identity')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_batch_account', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:primary_access_key, :secondary_access_key]
        expect(sensitive_fields).to include(:primary_access_key)
        expect(sensitive_fields).to include(:secondary_access_key)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts public_network_access_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(public_network_access_enabled: val)
          synth.azurerm_batch_account("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'azurerm_batch_account', "bool_#{val}")
          expect(config['public_network_access_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_batch_account', 'typed')
        expect(config['location']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['resource_group_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_batch_account('first', required_attrs)
        synth.azurerm_batch_account('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_batch_account')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_batch_account,
    method: :azurerm_batch_account,
    required_attrs: { location: 'test-value', name: 'test-value', resource_group_name: 'test-value' },
    expected_outputs: [:id, :account_endpoint, :allowed_authentication_modes, :primary_access_key, :secondary_access_key],
    sensitive_fields: [:primary_access_key, :secondary_access_key],
    immutable_fields: [],
    boolean_fields: [:public_network_access_enabled]
end
