# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_private_dns_zone resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzurePrivateDnsZone do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', resource_group_name: 'test-value' } }

  describe ':azurerm_private_dns_zone' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_private_dns_zone('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_private_dns_zone', 'test')
        validate_required_attributes(config, [:name, :resource_group_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_private_dns_zone('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_private_dns_zone)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_private_dns_zone('test', required_attrs)

        expect(ref.id).to eq("${azurerm_private_dns_zone.test.id}")
        expect(ref.max_number_of_record_sets).to eq("${azurerm_private_dns_zone.test.max_number_of_record_sets}")
        expect(ref.max_number_of_virtual_network_links).to eq("${azurerm_private_dns_zone.test.max_number_of_virtual_network_links}")
        expect(ref.max_number_of_virtual_network_links_with_registration).to eq("${azurerm_private_dns_zone.test.max_number_of_virtual_network_links_with_registration}")
        expect(ref.number_of_record_sets).to eq("${azurerm_private_dns_zone.test.number_of_record_sets}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_private_dns_zone('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_private_dns_zone', 'test')
        expect(config).not_to have_key('max_number_of_record_sets')
        expect(config).not_to have_key('max_number_of_virtual_network_links')
        expect(config).not_to have_key('max_number_of_virtual_network_links_with_registration')
        expect(config).not_to have_key('number_of_record_sets')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ soa_record: [{ 'key1' => 'val1' }], tags: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_private_dns_zone('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_private_dns_zone', 'full')
        expect(config).to have_key('soa_record')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes soa_record when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_private_dns_zone('opt', required_attrs.merge(soa_record: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_private_dns_zone', 'opt')
        expect(config).to have_key('soa_record')
      end

      it 'omits soa_record when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_private_dns_zone('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_private_dns_zone', 'minimal')
        expect(config).not_to have_key('soa_record')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_private_dns_zone('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_private_dns_zone', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_private_dns_zone('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_private_dns_zone', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_private_dns_zone('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_private_dns_zone', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['resource_group_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_private_dns_zone('first', required_attrs)
        synth.azurerm_private_dns_zone('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_private_dns_zone')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_private_dns_zone,
    method: :azurerm_private_dns_zone,
    required_attrs: { name: 'test-value', resource_group_name: 'test-value' },
    expected_outputs: [:id, :max_number_of_record_sets, :max_number_of_virtual_network_links, :max_number_of_virtual_network_links_with_registration, :number_of_record_sets],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
