# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_site_recovery_hyperv_replication_policy_association resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureSiteRecoveryHypervReplicationPolicyAssociation do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { hyperv_site_id: 'test-value', name: 'test-value', policy_id: 'test-value' } }

  describe ':azurerm_site_recovery_hyperv_replication_policy_association' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_site_recovery_hyperv_replication_policy_association('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_site_recovery_hyperv_replication_policy_association', 'test')
        validate_required_attributes(config, [:hyperv_site_id, :name, :policy_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_site_recovery_hyperv_replication_policy_association('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_site_recovery_hyperv_replication_policy_association)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_site_recovery_hyperv_replication_policy_association('test', required_attrs)

        expect(ref.id).to eq("${azurerm_site_recovery_hyperv_replication_policy_association.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_site_recovery_hyperv_replication_policy_association('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_site_recovery_hyperv_replication_policy_association', 'typed')
        expect(config['hyperv_site_id']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['policy_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_site_recovery_hyperv_replication_policy_association('first', required_attrs)
        synth.azurerm_site_recovery_hyperv_replication_policy_association('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_site_recovery_hyperv_replication_policy_association')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_site_recovery_hyperv_replication_policy_association,
    method: :azurerm_site_recovery_hyperv_replication_policy_association,
    required_attrs: { hyperv_site_id: 'test-value', name: 'test-value', policy_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
