# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_maintenance_assignment_dynamic_scope resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureMaintenanceAssignmentDynamicScope do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { filter: { 'key1' => 'val1' }, maintenance_configuration_id: 'test-value', name: 'test-value' } }

  describe ':azurerm_maintenance_assignment_dynamic_scope' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_maintenance_assignment_dynamic_scope('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_maintenance_assignment_dynamic_scope', 'test')
        validate_required_attributes(config, [:filter, :maintenance_configuration_id, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_maintenance_assignment_dynamic_scope('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_maintenance_assignment_dynamic_scope)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_maintenance_assignment_dynamic_scope('test', required_attrs)

        expect(ref.id).to eq("${azurerm_maintenance_assignment_dynamic_scope.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_maintenance_assignment_dynamic_scope('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_maintenance_assignment_dynamic_scope', 'typed')
        expect(config['filter']).to be_a(Hash)
        expect(config['maintenance_configuration_id']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_maintenance_assignment_dynamic_scope('first', required_attrs)
        synth.azurerm_maintenance_assignment_dynamic_scope('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_maintenance_assignment_dynamic_scope')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_maintenance_assignment_dynamic_scope,
    method: :azurerm_maintenance_assignment_dynamic_scope,
    required_attrs: { filter: { 'key1' => 'val1' }, maintenance_configuration_id: 'test-value', name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
