# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_automation_hybrid_runbook_worker_group resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureAutomationHybridRunbookWorkerGroup do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { automation_account_name: 'test-value', name: 'test-value', resource_group_name: 'test-value' } }

  describe ':azurerm_automation_hybrid_runbook_worker_group' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_automation_hybrid_runbook_worker_group('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_automation_hybrid_runbook_worker_group', 'test')
        validate_required_attributes(config, [:automation_account_name, :name, :resource_group_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_automation_hybrid_runbook_worker_group('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_automation_hybrid_runbook_worker_group)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_automation_hybrid_runbook_worker_group('test', required_attrs)

        expect(ref.id).to eq("${azurerm_automation_hybrid_runbook_worker_group.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ credential_name: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_automation_hybrid_runbook_worker_group('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_automation_hybrid_runbook_worker_group', 'full')
        expect(config).to have_key('credential_name')
      end
    end

    context 'optional attributes' do
      it 'includes credential_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_automation_hybrid_runbook_worker_group('opt', required_attrs.merge(credential_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_automation_hybrid_runbook_worker_group', 'opt')
        expect(config).to have_key('credential_name')
      end

      it 'omits credential_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_automation_hybrid_runbook_worker_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_automation_hybrid_runbook_worker_group', 'minimal')
        expect(config).not_to have_key('credential_name')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_automation_hybrid_runbook_worker_group('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_automation_hybrid_runbook_worker_group', 'typed')
        expect(config['automation_account_name']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['resource_group_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_automation_hybrid_runbook_worker_group('first', required_attrs)
        synth.azurerm_automation_hybrid_runbook_worker_group('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_automation_hybrid_runbook_worker_group')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_automation_hybrid_runbook_worker_group,
    method: :azurerm_automation_hybrid_runbook_worker_group,
    required_attrs: { automation_account_name: 'test-value', name: 'test-value', resource_group_name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
