# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_vpn_server_configuration resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureVpnServerConfiguration do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { location: 'test-value', name: 'test-value', resource_group_name: 'test-value', vpn_authentication_types: ['test-value'] } }

  describe ':azurerm_vpn_server_configuration' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_server_configuration('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_vpn_server_configuration', 'test')
        validate_required_attributes(config, [:location, :name, :resource_group_name, :vpn_authentication_types])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_vpn_server_configuration('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_vpn_server_configuration)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_vpn_server_configuration('test', required_attrs)

        expect(ref.id).to eq("${azurerm_vpn_server_configuration.test.id}")
        expect(ref.vpn_protocols).to eq("${azurerm_vpn_server_configuration.test.vpn_protocols}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_server_configuration('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_vpn_server_configuration', 'test')
        expect(config).not_to have_key('vpn_protocols')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ azure_active_directory_authentication: [{ 'key1' => 'val1' }], client_revoked_certificate: [{ 'key1' => 'val1' }], client_root_certificate: [{ 'key1' => 'val1' }], ipsec_policy: { 'key1' => 'val1' }, radius: { 'key1' => 'val1' }, tags: { 'key1' => 'val1' }, vpn_protocols: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_server_configuration('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_vpn_server_configuration', 'full')
        expect(config).to have_key('azure_active_directory_authentication')
        expect(config).to have_key('client_revoked_certificate')
        expect(config).to have_key('client_root_certificate')
        expect(config).to have_key('ipsec_policy')
        expect(config).to have_key('radius')
        expect(config).to have_key('tags')
        expect(config).to have_key('vpn_protocols')
      end
    end

    context 'optional attributes' do
      it 'includes azure_active_directory_authentication when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_server_configuration('opt', required_attrs.merge(azure_active_directory_authentication: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_server_configuration', 'opt')
        expect(config).to have_key('azure_active_directory_authentication')
      end

      it 'omits azure_active_directory_authentication when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_server_configuration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_server_configuration', 'minimal')
        expect(config).not_to have_key('azure_active_directory_authentication')
      end
      it 'includes client_revoked_certificate when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_server_configuration('opt', required_attrs.merge(client_revoked_certificate: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_server_configuration', 'opt')
        expect(config).to have_key('client_revoked_certificate')
      end

      it 'omits client_revoked_certificate when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_server_configuration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_server_configuration', 'minimal')
        expect(config).not_to have_key('client_revoked_certificate')
      end
      it 'includes client_root_certificate when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_server_configuration('opt', required_attrs.merge(client_root_certificate: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_server_configuration', 'opt')
        expect(config).to have_key('client_root_certificate')
      end

      it 'omits client_root_certificate when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_server_configuration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_server_configuration', 'minimal')
        expect(config).not_to have_key('client_root_certificate')
      end
      it 'includes ipsec_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_server_configuration('opt', required_attrs.merge(ipsec_policy: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_server_configuration', 'opt')
        expect(config).to have_key('ipsec_policy')
      end

      it 'omits ipsec_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_server_configuration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_server_configuration', 'minimal')
        expect(config).not_to have_key('ipsec_policy')
      end
      it 'includes radius when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_server_configuration('opt', required_attrs.merge(radius: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_server_configuration', 'opt')
        expect(config).to have_key('radius')
      end

      it 'omits radius when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_server_configuration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_server_configuration', 'minimal')
        expect(config).not_to have_key('radius')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_server_configuration('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_server_configuration', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_server_configuration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_server_configuration', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes vpn_protocols when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_server_configuration('opt', required_attrs.merge(vpn_protocols: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_server_configuration', 'opt')
        expect(config).to have_key('vpn_protocols')
      end

      it 'omits vpn_protocols when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_server_configuration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_server_configuration', 'minimal')
        expect(config).not_to have_key('vpn_protocols')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_server_configuration('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_vpn_server_configuration', 'typed')
        expect(config['location']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['resource_group_name']).to be_a(String)
        expect(config['vpn_authentication_types']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_server_configuration('first', required_attrs)
        synth.azurerm_vpn_server_configuration('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_vpn_server_configuration')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_vpn_server_configuration,
    method: :azurerm_vpn_server_configuration,
    required_attrs: { location: 'test-value', name: 'test-value', resource_group_name: 'test-value', vpn_authentication_types: ['test-value'] },
    expected_outputs: [:id, :vpn_protocols],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
