# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_api_management_workspace_api_version_set resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureApiManagementWorkspaceApiVersionSet do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { api_management_workspace_id: 'test-value', display_name: 'test-value', name: 'test-value', versioning_scheme: 'test-value' } }

  describe ':azurerm_api_management_workspace_api_version_set' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_api_management_workspace_api_version_set('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_api_management_workspace_api_version_set', 'test')
        validate_required_attributes(config, [:api_management_workspace_id, :display_name, :name, :versioning_scheme])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_api_management_workspace_api_version_set('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_api_management_workspace_api_version_set)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_api_management_workspace_api_version_set('test', required_attrs)

        expect(ref.id).to eq("${azurerm_api_management_workspace_api_version_set.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', version_header_name: 'test-value', version_query_name: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_api_management_workspace_api_version_set('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_api_management_workspace_api_version_set', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('version_header_name')
        expect(config).to have_key('version_query_name')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_api_management_workspace_api_version_set('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_api_management_workspace_api_version_set', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_api_management_workspace_api_version_set('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_api_management_workspace_api_version_set', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes version_header_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_api_management_workspace_api_version_set('opt', required_attrs.merge(version_header_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_api_management_workspace_api_version_set', 'opt')
        expect(config).to have_key('version_header_name')
      end

      it 'omits version_header_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_api_management_workspace_api_version_set('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_api_management_workspace_api_version_set', 'minimal')
        expect(config).not_to have_key('version_header_name')
      end
      it 'includes version_query_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_api_management_workspace_api_version_set('opt', required_attrs.merge(version_query_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_api_management_workspace_api_version_set', 'opt')
        expect(config).to have_key('version_query_name')
      end

      it 'omits version_query_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_api_management_workspace_api_version_set('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_api_management_workspace_api_version_set', 'minimal')
        expect(config).not_to have_key('version_query_name')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_api_management_workspace_api_version_set('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_api_management_workspace_api_version_set', 'typed')
        expect(config['api_management_workspace_id']).to be_a(String)
        expect(config['display_name']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['versioning_scheme']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_api_management_workspace_api_version_set('first', required_attrs)
        synth.azurerm_api_management_workspace_api_version_set('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_api_management_workspace_api_version_set')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_api_management_workspace_api_version_set,
    method: :azurerm_api_management_workspace_api_version_set,
    required_attrs: { api_management_workspace_id: 'test-value', display_name: 'test-value', name: 'test-value', versioning_scheme: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
