# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_static_site resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureStaticSite do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { location: 'test-value', name: 'test-value', resource_group_name: 'test-value' } }

  describe ':azurerm_static_site' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_static_site('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_static_site', 'test')
        validate_required_attributes(config, [:location, :name, :resource_group_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_static_site('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_static_site)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_static_site('test', required_attrs)

        expect(ref.id).to eq("${azurerm_static_site.test.id}")
        expect(ref.api_key).to eq("${azurerm_static_site.test.api_key}")
        expect(ref.default_host_name).to eq("${azurerm_static_site.test.default_host_name}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_static_site('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_static_site', 'test')
        expect(config).not_to have_key('api_key')
        expect(config).not_to have_key('default_host_name')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ app_settings: { 'key1' => 'val1' }, identity: { 'key1' => 'val1' }, sku_size: 'test-value', sku_tier: 'test-value', tags: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_static_site('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_static_site', 'full')
        expect(config).to have_key('app_settings')
        expect(config).to have_key('identity')
        expect(config).to have_key('sku_size')
        expect(config).to have_key('sku_tier')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes app_settings when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_static_site('opt', required_attrs.merge(app_settings: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_static_site', 'opt')
        expect(config).to have_key('app_settings')
      end

      it 'omits app_settings when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_static_site('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_static_site', 'minimal')
        expect(config).not_to have_key('app_settings')
      end
      it 'includes identity when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_static_site('opt', required_attrs.merge(identity: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_static_site', 'opt')
        expect(config).to have_key('identity')
      end

      it 'omits identity when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_static_site('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_static_site', 'minimal')
        expect(config).not_to have_key('identity')
      end
      it 'includes sku_size when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_static_site('opt', required_attrs.merge(sku_size: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_static_site', 'opt')
        expect(config).to have_key('sku_size')
      end

      it 'omits sku_size when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_static_site('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_static_site', 'minimal')
        expect(config).not_to have_key('sku_size')
      end
      it 'includes sku_tier when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_static_site('opt', required_attrs.merge(sku_tier: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_static_site', 'opt')
        expect(config).to have_key('sku_tier')
      end

      it 'omits sku_tier when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_static_site('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_static_site', 'minimal')
        expect(config).not_to have_key('sku_tier')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_static_site('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_static_site', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_static_site('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_static_site', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:api_key]
        expect(sensitive_fields).to include(:api_key)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_static_site('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_static_site', 'typed')
        expect(config['location']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['resource_group_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_static_site('first', required_attrs)
        synth.azurerm_static_site('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_static_site')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_static_site,
    method: :azurerm_static_site,
    required_attrs: { location: 'test-value', name: 'test-value', resource_group_name: 'test-value' },
    expected_outputs: [:id, :api_key, :default_host_name],
    sensitive_fields: [:api_key],
    immutable_fields: [],
    boolean_fields: []
end
