# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_mssql_virtual_machine_availability_group_listener resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureMssqlVirtualMachineAvailabilityGroupListener do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', replica: [{ 'key1' => 'val1' }], sql_virtual_machine_group_id: 'test-value' } }

  describe ':azurerm_mssql_virtual_machine_availability_group_listener' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_mssql_virtual_machine_availability_group_listener('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_mssql_virtual_machine_availability_group_listener', 'test')
        validate_required_attributes(config, [:name, :replica, :sql_virtual_machine_group_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_mssql_virtual_machine_availability_group_listener('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_mssql_virtual_machine_availability_group_listener)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_mssql_virtual_machine_availability_group_listener('test', required_attrs)

        expect(ref.id).to eq("${azurerm_mssql_virtual_machine_availability_group_listener.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ availability_group_name: 'test-value', load_balancer_configuration: [{ 'key1' => 'val1' }], multi_subnet_ip_configuration: [{ 'key1' => 'val1' }], port: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_mssql_virtual_machine_availability_group_listener('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_mssql_virtual_machine_availability_group_listener', 'full')
        expect(config).to have_key('availability_group_name')
        expect(config).to have_key('load_balancer_configuration')
        expect(config).to have_key('multi_subnet_ip_configuration')
        expect(config).to have_key('port')
      end
    end

    context 'optional attributes' do
      it 'includes availability_group_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_mssql_virtual_machine_availability_group_listener('opt', required_attrs.merge(availability_group_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_mssql_virtual_machine_availability_group_listener', 'opt')
        expect(config).to have_key('availability_group_name')
      end

      it 'omits availability_group_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_mssql_virtual_machine_availability_group_listener('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_mssql_virtual_machine_availability_group_listener', 'minimal')
        expect(config).not_to have_key('availability_group_name')
      end
      it 'includes load_balancer_configuration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_mssql_virtual_machine_availability_group_listener('opt', required_attrs.merge(load_balancer_configuration: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_mssql_virtual_machine_availability_group_listener', 'opt')
        expect(config).to have_key('load_balancer_configuration')
      end

      it 'omits load_balancer_configuration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_mssql_virtual_machine_availability_group_listener('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_mssql_virtual_machine_availability_group_listener', 'minimal')
        expect(config).not_to have_key('load_balancer_configuration')
      end
      it 'includes multi_subnet_ip_configuration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_mssql_virtual_machine_availability_group_listener('opt', required_attrs.merge(multi_subnet_ip_configuration: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_mssql_virtual_machine_availability_group_listener', 'opt')
        expect(config).to have_key('multi_subnet_ip_configuration')
      end

      it 'omits multi_subnet_ip_configuration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_mssql_virtual_machine_availability_group_listener('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_mssql_virtual_machine_availability_group_listener', 'minimal')
        expect(config).not_to have_key('multi_subnet_ip_configuration')
      end
      it 'includes port when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_mssql_virtual_machine_availability_group_listener('opt', required_attrs.merge(port: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_mssql_virtual_machine_availability_group_listener', 'opt')
        expect(config).to have_key('port')
      end

      it 'omits port when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_mssql_virtual_machine_availability_group_listener('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_mssql_virtual_machine_availability_group_listener', 'minimal')
        expect(config).not_to have_key('port')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_mssql_virtual_machine_availability_group_listener('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_mssql_virtual_machine_availability_group_listener', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['replica']).to be_a(Array)
        expect(config['sql_virtual_machine_group_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_mssql_virtual_machine_availability_group_listener('first', required_attrs)
        synth.azurerm_mssql_virtual_machine_availability_group_listener('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_mssql_virtual_machine_availability_group_listener')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_mssql_virtual_machine_availability_group_listener,
    method: :azurerm_mssql_virtual_machine_availability_group_listener,
    required_attrs: { name: 'test-value', replica: [{ 'key1' => 'val1' }], sql_virtual_machine_group_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
