# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_iothub_dps resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureIothubDps do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { location: 'test-value', name: 'test-value', resource_group_name: 'test-value', sku: [{ 'key1' => 'val1' }] } }

  describe ':azurerm_iothub_dps' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_iothub_dps('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_iothub_dps', 'test')
        validate_required_attributes(config, [:location, :name, :resource_group_name, :sku])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_iothub_dps('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_iothub_dps)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_iothub_dps('test', required_attrs)

        expect(ref.id).to eq("${azurerm_iothub_dps.test.id}")
        expect(ref.device_provisioning_host_name).to eq("${azurerm_iothub_dps.test.device_provisioning_host_name}")
        expect(ref.id_scope).to eq("${azurerm_iothub_dps.test.id_scope}")
        expect(ref.service_operations_host_name).to eq("${azurerm_iothub_dps.test.service_operations_host_name}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_iothub_dps('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_iothub_dps', 'test')
        expect(config).not_to have_key('device_provisioning_host_name')
        expect(config).not_to have_key('id_scope')
        expect(config).not_to have_key('service_operations_host_name')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allocation_policy: 'test-value', data_residency_enabled: true, ip_filter_rule: [{ 'key1' => 'val1' }], linked_hub: [{ 'key1' => 'val1' }], public_network_access_enabled: true, tags: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_iothub_dps('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_iothub_dps', 'full')
        expect(config).to have_key('allocation_policy')
        expect(config).to have_key('data_residency_enabled')
        expect(config).to have_key('ip_filter_rule')
        expect(config).to have_key('linked_hub')
        expect(config).to have_key('public_network_access_enabled')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes allocation_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_iothub_dps('opt', required_attrs.merge(allocation_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_iothub_dps', 'opt')
        expect(config).to have_key('allocation_policy')
      end

      it 'omits allocation_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_iothub_dps('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_iothub_dps', 'minimal')
        expect(config).not_to have_key('allocation_policy')
      end
      it 'includes data_residency_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_iothub_dps('opt', required_attrs.merge(data_residency_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_iothub_dps', 'opt')
        expect(config).to have_key('data_residency_enabled')
      end

      it 'omits data_residency_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_iothub_dps('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_iothub_dps', 'minimal')
        expect(config).not_to have_key('data_residency_enabled')
      end
      it 'includes ip_filter_rule when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_iothub_dps('opt', required_attrs.merge(ip_filter_rule: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_iothub_dps', 'opt')
        expect(config).to have_key('ip_filter_rule')
      end

      it 'omits ip_filter_rule when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_iothub_dps('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_iothub_dps', 'minimal')
        expect(config).not_to have_key('ip_filter_rule')
      end
      it 'includes linked_hub when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_iothub_dps('opt', required_attrs.merge(linked_hub: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_iothub_dps', 'opt')
        expect(config).to have_key('linked_hub')
      end

      it 'omits linked_hub when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_iothub_dps('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_iothub_dps', 'minimal')
        expect(config).not_to have_key('linked_hub')
      end
      it 'includes public_network_access_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_iothub_dps('opt', required_attrs.merge(public_network_access_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_iothub_dps', 'opt')
        expect(config).to have_key('public_network_access_enabled')
      end

      it 'omits public_network_access_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_iothub_dps('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_iothub_dps', 'minimal')
        expect(config).not_to have_key('public_network_access_enabled')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_iothub_dps('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_iothub_dps', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_iothub_dps('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_iothub_dps', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts data_residency_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(data_residency_enabled: val)
          synth.azurerm_iothub_dps("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'azurerm_iothub_dps', "bool_#{val}")
          expect(config['data_residency_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts public_network_access_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(public_network_access_enabled: val)
          synth.azurerm_iothub_dps("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'azurerm_iothub_dps', "bool_#{val}")
          expect(config['public_network_access_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_iothub_dps('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_iothub_dps', 'typed')
        expect(config['location']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['resource_group_name']).to be_a(String)
        expect(config['sku']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_iothub_dps('first', required_attrs)
        synth.azurerm_iothub_dps('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_iothub_dps')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_iothub_dps,
    method: :azurerm_iothub_dps,
    required_attrs: { location: 'test-value', name: 'test-value', resource_group_name: 'test-value', sku: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id, :device_provisioning_host_name, :id_scope, :service_operations_host_name],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:data_residency_enabled, :public_network_access_enabled]
end
