# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_storage_blob_inventory_policy resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureStorageBlobInventoryPolicy do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { rules: [{ 'key1' => 'val1' }], storage_account_id: 'test-value' } }

  describe ':azurerm_storage_blob_inventory_policy' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_storage_blob_inventory_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_storage_blob_inventory_policy', 'test')
        validate_required_attributes(config, [:rules, :storage_account_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_storage_blob_inventory_policy('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_storage_blob_inventory_policy)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_storage_blob_inventory_policy('test', required_attrs)

        expect(ref.id).to eq("${azurerm_storage_blob_inventory_policy.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_storage_blob_inventory_policy('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_storage_blob_inventory_policy', 'typed')
        expect(config['rules']).to be_a(Array)
        expect(config['storage_account_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_storage_blob_inventory_policy('first', required_attrs)
        synth.azurerm_storage_blob_inventory_policy('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_storage_blob_inventory_policy')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_storage_blob_inventory_policy,
    method: :azurerm_storage_blob_inventory_policy,
    required_attrs: { rules: [{ 'key1' => 'val1' }], storage_account_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
