# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_spring_cloud_configuration_service resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureSpringCloudConfigurationService do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', spring_cloud_service_id: 'test-value' } }

  describe ':azurerm_spring_cloud_configuration_service' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_configuration_service('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_configuration_service', 'test')
        validate_required_attributes(config, [:name, :spring_cloud_service_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_spring_cloud_configuration_service('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_spring_cloud_configuration_service)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_spring_cloud_configuration_service('test', required_attrs)

        expect(ref.id).to eq("${azurerm_spring_cloud_configuration_service.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ generation: 'test-value', refresh_interval_in_seconds: 3.14, repository: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_configuration_service('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_spring_cloud_configuration_service', 'full')
        expect(config).to have_key('generation')
        expect(config).to have_key('refresh_interval_in_seconds')
        expect(config).to have_key('repository')
      end
    end

    context 'optional attributes' do
      it 'includes generation when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_configuration_service('opt', required_attrs.merge(generation: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_configuration_service', 'opt')
        expect(config).to have_key('generation')
      end

      it 'omits generation when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_configuration_service('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_configuration_service', 'minimal')
        expect(config).not_to have_key('generation')
      end
      it 'includes refresh_interval_in_seconds when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_configuration_service('opt', required_attrs.merge(refresh_interval_in_seconds: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_configuration_service', 'opt')
        expect(config).to have_key('refresh_interval_in_seconds')
      end

      it 'omits refresh_interval_in_seconds when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_configuration_service('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_configuration_service', 'minimal')
        expect(config).not_to have_key('refresh_interval_in_seconds')
      end
      it 'includes repository when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_configuration_service('opt', required_attrs.merge(repository: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_configuration_service', 'opt')
        expect(config).to have_key('repository')
      end

      it 'omits repository when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_configuration_service('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_configuration_service', 'minimal')
        expect(config).not_to have_key('repository')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_configuration_service('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_spring_cloud_configuration_service', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['spring_cloud_service_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_configuration_service('first', required_attrs)
        synth.azurerm_spring_cloud_configuration_service('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_spring_cloud_configuration_service')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_spring_cloud_configuration_service,
    method: :azurerm_spring_cloud_configuration_service,
    required_attrs: { name: 'test-value', spring_cloud_service_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
