# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_eventgrid_partner_registration resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureEventgridPartnerRegistration do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', resource_group_name: 'test-value' } }

  describe ':azurerm_eventgrid_partner_registration' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_eventgrid_partner_registration('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_eventgrid_partner_registration', 'test')
        validate_required_attributes(config, [:name, :resource_group_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_eventgrid_partner_registration('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_eventgrid_partner_registration)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_eventgrid_partner_registration('test', required_attrs)

        expect(ref.id).to eq("${azurerm_eventgrid_partner_registration.test.id}")
        expect(ref.partner_registration_id).to eq("${azurerm_eventgrid_partner_registration.test.partner_registration_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_eventgrid_partner_registration('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_eventgrid_partner_registration', 'test')
        expect(config).not_to have_key('partner_registration_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ tags: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_eventgrid_partner_registration('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_eventgrid_partner_registration', 'full')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_eventgrid_partner_registration('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_eventgrid_partner_registration', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_eventgrid_partner_registration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_eventgrid_partner_registration', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_eventgrid_partner_registration('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_eventgrid_partner_registration', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['resource_group_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_eventgrid_partner_registration('first', required_attrs)
        synth.azurerm_eventgrid_partner_registration('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_eventgrid_partner_registration')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_eventgrid_partner_registration,
    method: :azurerm_eventgrid_partner_registration,
    required_attrs: { name: 'test-value', resource_group_name: 'test-value' },
    expected_outputs: [:id, :partner_registration_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
