# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_spring_cloud_new_relic_application_performance_monitoring resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureSpringCloudNewRelicApplicationPerformanceMonitoring do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { app_name: 'test-value', license_key: 'test-value', name: 'test-value', spring_cloud_service_id: 'test-value' } }

  describe ':azurerm_spring_cloud_new_relic_application_performance_monitoring' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', 'test')
        validate_required_attributes(config, [:app_name, :license_key, :name, :spring_cloud_service_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_spring_cloud_new_relic_application_performance_monitoring)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('test', required_attrs)

        expect(ref.id).to eq("${azurerm_spring_cloud_new_relic_application_performance_monitoring.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ agent_enabled: true, app_server_port: 3.14, audit_mode_enabled: true, auto_app_naming_enabled: true, auto_transaction_naming_enabled: true, custom_tracing_enabled: true, globally_enabled: true, labels: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', 'full')
        expect(config).to have_key('agent_enabled')
        expect(config).to have_key('app_server_port')
        expect(config).to have_key('audit_mode_enabled')
        expect(config).to have_key('auto_app_naming_enabled')
        expect(config).to have_key('auto_transaction_naming_enabled')
        expect(config).to have_key('custom_tracing_enabled')
        expect(config).to have_key('globally_enabled')
        expect(config).to have_key('labels')
      end
    end

    context 'optional attributes' do
      it 'includes agent_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('opt', required_attrs.merge(agent_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', 'opt')
        expect(config).to have_key('agent_enabled')
      end

      it 'omits agent_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', 'minimal')
        expect(config).not_to have_key('agent_enabled')
      end
      it 'includes app_server_port when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('opt', required_attrs.merge(app_server_port: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', 'opt')
        expect(config).to have_key('app_server_port')
      end

      it 'omits app_server_port when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', 'minimal')
        expect(config).not_to have_key('app_server_port')
      end
      it 'includes audit_mode_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('opt', required_attrs.merge(audit_mode_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', 'opt')
        expect(config).to have_key('audit_mode_enabled')
      end

      it 'omits audit_mode_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', 'minimal')
        expect(config).not_to have_key('audit_mode_enabled')
      end
      it 'includes auto_app_naming_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('opt', required_attrs.merge(auto_app_naming_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', 'opt')
        expect(config).to have_key('auto_app_naming_enabled')
      end

      it 'omits auto_app_naming_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', 'minimal')
        expect(config).not_to have_key('auto_app_naming_enabled')
      end
      it 'includes auto_transaction_naming_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('opt', required_attrs.merge(auto_transaction_naming_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', 'opt')
        expect(config).to have_key('auto_transaction_naming_enabled')
      end

      it 'omits auto_transaction_naming_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', 'minimal')
        expect(config).not_to have_key('auto_transaction_naming_enabled')
      end
      it 'includes custom_tracing_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('opt', required_attrs.merge(custom_tracing_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', 'opt')
        expect(config).to have_key('custom_tracing_enabled')
      end

      it 'omits custom_tracing_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', 'minimal')
        expect(config).not_to have_key('custom_tracing_enabled')
      end
      it 'includes globally_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('opt', required_attrs.merge(globally_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', 'opt')
        expect(config).to have_key('globally_enabled')
      end

      it 'omits globally_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', 'minimal')
        expect(config).not_to have_key('globally_enabled')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('opt', required_attrs.merge(labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', 'minimal')
        expect(config).not_to have_key('labels')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:license_key]
        expect(sensitive_fields).to include(:license_key)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts agent_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(agent_enabled: val)
          synth.azurerm_spring_cloud_new_relic_application_performance_monitoring("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', "bool_#{val}")
          expect(config['agent_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts audit_mode_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(audit_mode_enabled: val)
          synth.azurerm_spring_cloud_new_relic_application_performance_monitoring("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', "bool_#{val}")
          expect(config['audit_mode_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts auto_app_naming_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(auto_app_naming_enabled: val)
          synth.azurerm_spring_cloud_new_relic_application_performance_monitoring("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', "bool_#{val}")
          expect(config['auto_app_naming_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts auto_transaction_naming_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(auto_transaction_naming_enabled: val)
          synth.azurerm_spring_cloud_new_relic_application_performance_monitoring("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', "bool_#{val}")
          expect(config['auto_transaction_naming_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts custom_tracing_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(custom_tracing_enabled: val)
          synth.azurerm_spring_cloud_new_relic_application_performance_monitoring("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', "bool_#{val}")
          expect(config['custom_tracing_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts globally_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(globally_enabled: val)
          synth.azurerm_spring_cloud_new_relic_application_performance_monitoring("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', "bool_#{val}")
          expect(config['globally_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_spring_cloud_new_relic_application_performance_monitoring', 'typed')
        expect(config['app_name']).to be_a(String)
        expect(config['license_key']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['spring_cloud_service_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('first', required_attrs)
        synth.azurerm_spring_cloud_new_relic_application_performance_monitoring('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_spring_cloud_new_relic_application_performance_monitoring')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_spring_cloud_new_relic_application_performance_monitoring,
    method: :azurerm_spring_cloud_new_relic_application_performance_monitoring,
    required_attrs: { app_name: 'test-value', license_key: 'test-value', name: 'test-value', spring_cloud_service_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [:license_key],
    immutable_fields: [],
    boolean_fields: [:agent_enabled, :audit_mode_enabled, :auto_app_naming_enabled, :auto_transaction_naming_enabled, :custom_tracing_enabled, :globally_enabled]
end
