# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_synapse_workspace resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureSynapseWorkspace do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { location: 'test-value', name: 'test-value', resource_group_name: 'test-value', storage_data_lake_gen2_filesystem_id: 'test-value' } }

  describe ':azurerm_synapse_workspace' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'test')
        validate_required_attributes(config, [:location, :name, :resource_group_name, :storage_data_lake_gen2_filesystem_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_synapse_workspace('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_synapse_workspace)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_synapse_workspace('test', required_attrs)

        expect(ref.id).to eq("${azurerm_synapse_workspace.test.id}")
        expect(ref.connectivity_endpoints).to eq("${azurerm_synapse_workspace.test.connectivity_endpoints}")
        expect(ref.managed_resource_group_name).to eq("${azurerm_synapse_workspace.test.managed_resource_group_name}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'test')
        expect(config).not_to have_key('connectivity_endpoints')
        expect(config).not_to have_key('managed_resource_group_name')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ azure_devops_repo: { 'key1' => 'val1' }, azuread_authentication_only: true, compute_subnet_id: 'test-value', customer_managed_key: { 'key1' => 'val1' }, data_exfiltration_protection_enabled: true, github_repo: { 'key1' => 'val1' }, identity: { 'key1' => 'val1' }, linking_allowed_for_aad_tenant_ids: ['test-value'], managed_resource_group_name: 'test-value', managed_virtual_network_enabled: true, public_network_access_enabled: true, purview_id: 'test-value', sql_administrator_login: 'test-value', sql_administrator_login_password: 'test-value', sql_identity_control_enabled: true, tags: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'full')
        expect(config).to have_key('azure_devops_repo')
        expect(config).to have_key('azuread_authentication_only')
        expect(config).to have_key('compute_subnet_id')
        expect(config).to have_key('customer_managed_key')
        expect(config).to have_key('data_exfiltration_protection_enabled')
        expect(config).to have_key('github_repo')
        expect(config).to have_key('identity')
        expect(config).to have_key('linking_allowed_for_aad_tenant_ids')
        expect(config).to have_key('managed_resource_group_name')
        expect(config).to have_key('managed_virtual_network_enabled')
        expect(config).to have_key('public_network_access_enabled')
        expect(config).to have_key('purview_id')
        expect(config).to have_key('sql_administrator_login')
        expect(config).to have_key('sql_administrator_login_password')
        expect(config).to have_key('sql_identity_control_enabled')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes azure_devops_repo when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('opt', required_attrs.merge(azure_devops_repo: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'opt')
        expect(config).to have_key('azure_devops_repo')
      end

      it 'omits azure_devops_repo when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'minimal')
        expect(config).not_to have_key('azure_devops_repo')
      end
      it 'includes azuread_authentication_only when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('opt', required_attrs.merge(azuread_authentication_only: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'opt')
        expect(config).to have_key('azuread_authentication_only')
      end

      it 'omits azuread_authentication_only when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'minimal')
        expect(config).not_to have_key('azuread_authentication_only')
      end
      it 'includes compute_subnet_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('opt', required_attrs.merge(compute_subnet_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'opt')
        expect(config).to have_key('compute_subnet_id')
      end

      it 'omits compute_subnet_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'minimal')
        expect(config).not_to have_key('compute_subnet_id')
      end
      it 'includes customer_managed_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('opt', required_attrs.merge(customer_managed_key: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'opt')
        expect(config).to have_key('customer_managed_key')
      end

      it 'omits customer_managed_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'minimal')
        expect(config).not_to have_key('customer_managed_key')
      end
      it 'includes data_exfiltration_protection_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('opt', required_attrs.merge(data_exfiltration_protection_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'opt')
        expect(config).to have_key('data_exfiltration_protection_enabled')
      end

      it 'omits data_exfiltration_protection_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'minimal')
        expect(config).not_to have_key('data_exfiltration_protection_enabled')
      end
      it 'includes github_repo when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('opt', required_attrs.merge(github_repo: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'opt')
        expect(config).to have_key('github_repo')
      end

      it 'omits github_repo when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'minimal')
        expect(config).not_to have_key('github_repo')
      end
      it 'includes identity when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('opt', required_attrs.merge(identity: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'opt')
        expect(config).to have_key('identity')
      end

      it 'omits identity when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'minimal')
        expect(config).not_to have_key('identity')
      end
      it 'includes linking_allowed_for_aad_tenant_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('opt', required_attrs.merge(linking_allowed_for_aad_tenant_ids: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'opt')
        expect(config).to have_key('linking_allowed_for_aad_tenant_ids')
      end

      it 'omits linking_allowed_for_aad_tenant_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'minimal')
        expect(config).not_to have_key('linking_allowed_for_aad_tenant_ids')
      end
      it 'includes managed_resource_group_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('opt', required_attrs.merge(managed_resource_group_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'opt')
        expect(config).to have_key('managed_resource_group_name')
      end

      it 'omits managed_resource_group_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'minimal')
        expect(config).not_to have_key('managed_resource_group_name')
      end
      it 'includes managed_virtual_network_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('opt', required_attrs.merge(managed_virtual_network_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'opt')
        expect(config).to have_key('managed_virtual_network_enabled')
      end

      it 'omits managed_virtual_network_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'minimal')
        expect(config).not_to have_key('managed_virtual_network_enabled')
      end
      it 'includes public_network_access_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('opt', required_attrs.merge(public_network_access_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'opt')
        expect(config).to have_key('public_network_access_enabled')
      end

      it 'omits public_network_access_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'minimal')
        expect(config).not_to have_key('public_network_access_enabled')
      end
      it 'includes purview_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('opt', required_attrs.merge(purview_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'opt')
        expect(config).to have_key('purview_id')
      end

      it 'omits purview_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'minimal')
        expect(config).not_to have_key('purview_id')
      end
      it 'includes sql_administrator_login when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('opt', required_attrs.merge(sql_administrator_login: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'opt')
        expect(config).to have_key('sql_administrator_login')
      end

      it 'omits sql_administrator_login when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'minimal')
        expect(config).not_to have_key('sql_administrator_login')
      end
      it 'includes sql_administrator_login_password when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('opt', required_attrs.merge(sql_administrator_login_password: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'opt')
        expect(config).to have_key('sql_administrator_login_password')
      end

      it 'omits sql_administrator_login_password when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'minimal')
        expect(config).not_to have_key('sql_administrator_login_password')
      end
      it 'includes sql_identity_control_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('opt', required_attrs.merge(sql_identity_control_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'opt')
        expect(config).to have_key('sql_identity_control_enabled')
      end

      it 'omits sql_identity_control_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'minimal')
        expect(config).not_to have_key('sql_identity_control_enabled')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:sql_administrator_login_password]
        expect(sensitive_fields).to include(:sql_administrator_login_password)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts azuread_authentication_only=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(azuread_authentication_only: val)
          synth.azurerm_synapse_workspace("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'azurerm_synapse_workspace', "bool_#{val}")
          expect(config['azuread_authentication_only']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts data_exfiltration_protection_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(data_exfiltration_protection_enabled: val)
          synth.azurerm_synapse_workspace("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'azurerm_synapse_workspace', "bool_#{val}")
          expect(config['data_exfiltration_protection_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts managed_virtual_network_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(managed_virtual_network_enabled: val)
          synth.azurerm_synapse_workspace("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'azurerm_synapse_workspace', "bool_#{val}")
          expect(config['managed_virtual_network_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts public_network_access_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(public_network_access_enabled: val)
          synth.azurerm_synapse_workspace("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'azurerm_synapse_workspace', "bool_#{val}")
          expect(config['public_network_access_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts sql_identity_control_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(sql_identity_control_enabled: val)
          synth.azurerm_synapse_workspace("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'azurerm_synapse_workspace', "bool_#{val}")
          expect(config['sql_identity_control_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_synapse_workspace', 'typed')
        expect(config['location']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['resource_group_name']).to be_a(String)
        expect(config['storage_data_lake_gen2_filesystem_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_synapse_workspace('first', required_attrs)
        synth.azurerm_synapse_workspace('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_synapse_workspace')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_synapse_workspace,
    method: :azurerm_synapse_workspace,
    required_attrs: { location: 'test-value', name: 'test-value', resource_group_name: 'test-value', storage_data_lake_gen2_filesystem_id: 'test-value' },
    expected_outputs: [:id, :connectivity_endpoints, :managed_resource_group_name],
    sensitive_fields: [:sql_administrator_login_password],
    immutable_fields: [],
    boolean_fields: [:azuread_authentication_only, :data_exfiltration_protection_enabled, :managed_virtual_network_enabled, :public_network_access_enabled, :sql_identity_control_enabled]
end
