# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_mssql_virtual_network_rule resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureMssqlVirtualNetworkRule do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', server_id: 'test-value', subnet_id: 'test-value' } }

  describe ':azurerm_mssql_virtual_network_rule' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_mssql_virtual_network_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_mssql_virtual_network_rule', 'test')
        validate_required_attributes(config, [:name, :server_id, :subnet_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_mssql_virtual_network_rule('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_mssql_virtual_network_rule)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_mssql_virtual_network_rule('test', required_attrs)

        expect(ref.id).to eq("${azurerm_mssql_virtual_network_rule.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ ignore_missing_vnet_service_endpoint: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_mssql_virtual_network_rule('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_mssql_virtual_network_rule', 'full')
        expect(config).to have_key('ignore_missing_vnet_service_endpoint')
      end
    end

    context 'optional attributes' do
      it 'includes ignore_missing_vnet_service_endpoint when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_mssql_virtual_network_rule('opt', required_attrs.merge(ignore_missing_vnet_service_endpoint: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_mssql_virtual_network_rule', 'opt')
        expect(config).to have_key('ignore_missing_vnet_service_endpoint')
      end

      it 'omits ignore_missing_vnet_service_endpoint when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_mssql_virtual_network_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_mssql_virtual_network_rule', 'minimal')
        expect(config).not_to have_key('ignore_missing_vnet_service_endpoint')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts ignore_missing_vnet_service_endpoint=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(ignore_missing_vnet_service_endpoint: val)
          synth.azurerm_mssql_virtual_network_rule("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'azurerm_mssql_virtual_network_rule', "bool_#{val}")
          expect(config['ignore_missing_vnet_service_endpoint']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_mssql_virtual_network_rule('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_mssql_virtual_network_rule', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['server_id']).to be_a(String)
        expect(config['subnet_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_mssql_virtual_network_rule('first', required_attrs)
        synth.azurerm_mssql_virtual_network_rule('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_mssql_virtual_network_rule')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_mssql_virtual_network_rule,
    method: :azurerm_mssql_virtual_network_rule,
    required_attrs: { name: 'test-value', server_id: 'test-value', subnet_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:ignore_missing_vnet_service_endpoint]
end
