# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_web_pubsub_custom_domain resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureWebPubsubCustomDomain do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { domain_name: 'test-value', name: 'test-value', web_pubsub_custom_certificate_id: 'test-value', web_pubsub_id: 'test-value' } }

  describe ':azurerm_web_pubsub_custom_domain' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_web_pubsub_custom_domain('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_web_pubsub_custom_domain', 'test')
        validate_required_attributes(config, [:domain_name, :name, :web_pubsub_custom_certificate_id, :web_pubsub_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_web_pubsub_custom_domain('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_web_pubsub_custom_domain)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_web_pubsub_custom_domain('test', required_attrs)

        expect(ref.id).to eq("${azurerm_web_pubsub_custom_domain.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_web_pubsub_custom_domain('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_web_pubsub_custom_domain', 'typed')
        expect(config['domain_name']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['web_pubsub_custom_certificate_id']).to be_a(String)
        expect(config['web_pubsub_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_web_pubsub_custom_domain('first', required_attrs)
        synth.azurerm_web_pubsub_custom_domain('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_web_pubsub_custom_domain')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_web_pubsub_custom_domain,
    method: :azurerm_web_pubsub_custom_domain,
    required_attrs: { domain_name: 'test-value', name: 'test-value', web_pubsub_custom_certificate_id: 'test-value', web_pubsub_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
