# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_maps_account resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureMapsAccount do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { location: 'test-value', name: 'test-value', resource_group_name: 'test-value', sku_name: 'test-value' } }

  describe ':azurerm_maps_account' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_maps_account('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_maps_account', 'test')
        validate_required_attributes(config, [:location, :name, :resource_group_name, :sku_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_maps_account('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_maps_account)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_maps_account('test', required_attrs)

        expect(ref.id).to eq("${azurerm_maps_account.test.id}")
        expect(ref.primary_access_key).to eq("${azurerm_maps_account.test.primary_access_key}")
        expect(ref.secondary_access_key).to eq("${azurerm_maps_account.test.secondary_access_key}")
        expect(ref.x_ms_client_id).to eq("${azurerm_maps_account.test.x_ms_client_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_maps_account('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_maps_account', 'test')
        expect(config).not_to have_key('primary_access_key')
        expect(config).not_to have_key('secondary_access_key')
        expect(config).not_to have_key('x_ms_client_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ cors: [{ 'key1' => 'val1' }], data_store: [{ 'key1' => 'val1' }], identity: [{ 'key1' => 'val1' }], local_authentication_enabled: true, tags: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_maps_account('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_maps_account', 'full')
        expect(config).to have_key('cors')
        expect(config).to have_key('data_store')
        expect(config).to have_key('identity')
        expect(config).to have_key('local_authentication_enabled')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes cors when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_maps_account('opt', required_attrs.merge(cors: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_maps_account', 'opt')
        expect(config).to have_key('cors')
      end

      it 'omits cors when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_maps_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_maps_account', 'minimal')
        expect(config).not_to have_key('cors')
      end
      it 'includes data_store when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_maps_account('opt', required_attrs.merge(data_store: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_maps_account', 'opt')
        expect(config).to have_key('data_store')
      end

      it 'omits data_store when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_maps_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_maps_account', 'minimal')
        expect(config).not_to have_key('data_store')
      end
      it 'includes identity when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_maps_account('opt', required_attrs.merge(identity: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_maps_account', 'opt')
        expect(config).to have_key('identity')
      end

      it 'omits identity when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_maps_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_maps_account', 'minimal')
        expect(config).not_to have_key('identity')
      end
      it 'includes local_authentication_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_maps_account('opt', required_attrs.merge(local_authentication_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_maps_account', 'opt')
        expect(config).to have_key('local_authentication_enabled')
      end

      it 'omits local_authentication_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_maps_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_maps_account', 'minimal')
        expect(config).not_to have_key('local_authentication_enabled')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_maps_account('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_maps_account', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_maps_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_maps_account', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:primary_access_key, :secondary_access_key]
        expect(sensitive_fields).to include(:primary_access_key)
        expect(sensitive_fields).to include(:secondary_access_key)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts local_authentication_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(local_authentication_enabled: val)
          synth.azurerm_maps_account("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'azurerm_maps_account', "bool_#{val}")
          expect(config['local_authentication_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_maps_account('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_maps_account', 'typed')
        expect(config['location']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['resource_group_name']).to be_a(String)
        expect(config['sku_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_maps_account('first', required_attrs)
        synth.azurerm_maps_account('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_maps_account')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_maps_account,
    method: :azurerm_maps_account,
    required_attrs: { location: 'test-value', name: 'test-value', resource_group_name: 'test-value', sku_name: 'test-value' },
    expected_outputs: [:id, :primary_access_key, :secondary_access_key, :x_ms_client_id],
    sensitive_fields: [:primary_access_key, :secondary_access_key],
    immutable_fields: [],
    boolean_fields: [:local_authentication_enabled]
end
