# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_vpn_gateway_nat_rule resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureVpnGatewayNatRule do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', vpn_gateway_id: 'test-value' } }

  describe ':azurerm_vpn_gateway_nat_rule' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_gateway_nat_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_vpn_gateway_nat_rule', 'test')
        validate_required_attributes(config, [:name, :vpn_gateway_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_vpn_gateway_nat_rule('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_vpn_gateway_nat_rule)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_vpn_gateway_nat_rule('test', required_attrs)

        expect(ref.id).to eq("${azurerm_vpn_gateway_nat_rule.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ external_mapping: [{ 'key1' => 'val1' }], internal_mapping: [{ 'key1' => 'val1' }], ip_configuration_id: 'test-value', mode: 'test-value', type: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_gateway_nat_rule('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_vpn_gateway_nat_rule', 'full')
        expect(config).to have_key('external_mapping')
        expect(config).to have_key('internal_mapping')
        expect(config).to have_key('ip_configuration_id')
        expect(config).to have_key('mode')
        expect(config).to have_key('type')
      end
    end

    context 'optional attributes' do
      it 'includes external_mapping when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_gateway_nat_rule('opt', required_attrs.merge(external_mapping: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_gateway_nat_rule', 'opt')
        expect(config).to have_key('external_mapping')
      end

      it 'omits external_mapping when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_gateway_nat_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_gateway_nat_rule', 'minimal')
        expect(config).not_to have_key('external_mapping')
      end
      it 'includes internal_mapping when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_gateway_nat_rule('opt', required_attrs.merge(internal_mapping: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_gateway_nat_rule', 'opt')
        expect(config).to have_key('internal_mapping')
      end

      it 'omits internal_mapping when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_gateway_nat_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_gateway_nat_rule', 'minimal')
        expect(config).not_to have_key('internal_mapping')
      end
      it 'includes ip_configuration_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_gateway_nat_rule('opt', required_attrs.merge(ip_configuration_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_gateway_nat_rule', 'opt')
        expect(config).to have_key('ip_configuration_id')
      end

      it 'omits ip_configuration_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_gateway_nat_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_gateway_nat_rule', 'minimal')
        expect(config).not_to have_key('ip_configuration_id')
      end
      it 'includes mode when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_gateway_nat_rule('opt', required_attrs.merge(mode: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_gateway_nat_rule', 'opt')
        expect(config).to have_key('mode')
      end

      it 'omits mode when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_gateway_nat_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_gateway_nat_rule', 'minimal')
        expect(config).not_to have_key('mode')
      end
      it 'includes type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_gateway_nat_rule('opt', required_attrs.merge(type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_gateway_nat_rule', 'opt')
        expect(config).to have_key('type')
      end

      it 'omits type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_gateway_nat_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_vpn_gateway_nat_rule', 'minimal')
        expect(config).not_to have_key('type')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_gateway_nat_rule('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_vpn_gateway_nat_rule', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['vpn_gateway_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_vpn_gateway_nat_rule('first', required_attrs)
        synth.azurerm_vpn_gateway_nat_rule('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_vpn_gateway_nat_rule')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_vpn_gateway_nat_rule,
    method: :azurerm_vpn_gateway_nat_rule,
    required_attrs: { name: 'test-value', vpn_gateway_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
