# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_marketplace_role_assignment resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureMarketplaceRoleAssignment do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { principal_id: 'test-value' } }

  describe ':azurerm_marketplace_role_assignment' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_marketplace_role_assignment('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_marketplace_role_assignment', 'test')
        validate_required_attributes(config, [:principal_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_marketplace_role_assignment('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_marketplace_role_assignment)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_marketplace_role_assignment('test', required_attrs)

        expect(ref.id).to eq("${azurerm_marketplace_role_assignment.test.id}")
        expect(ref.principal_type).to eq("${azurerm_marketplace_role_assignment.test.principal_type}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_marketplace_role_assignment('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_marketplace_role_assignment', 'test')
        expect(config).not_to have_key('principal_type')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ condition: 'test-value', condition_version: 'test-value', delegated_managed_identity_resource_id: 'test-value', description: 'test-value', name: 'test-value', role_definition_id: 'test-value', role_definition_name: 'test-value', skip_service_principal_aad_check: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_marketplace_role_assignment('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_marketplace_role_assignment', 'full')
        expect(config).to have_key('condition')
        expect(config).to have_key('condition_version')
        expect(config).to have_key('delegated_managed_identity_resource_id')
        expect(config).to have_key('description')
        expect(config).to have_key('name')
        expect(config).to have_key('role_definition_id')
        expect(config).to have_key('role_definition_name')
        expect(config).to have_key('skip_service_principal_aad_check')
      end
    end

    context 'optional attributes' do
      it 'includes condition when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_marketplace_role_assignment('opt', required_attrs.merge(condition: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_marketplace_role_assignment', 'opt')
        expect(config).to have_key('condition')
      end

      it 'omits condition when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_marketplace_role_assignment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_marketplace_role_assignment', 'minimal')
        expect(config).not_to have_key('condition')
      end
      it 'includes condition_version when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_marketplace_role_assignment('opt', required_attrs.merge(condition_version: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_marketplace_role_assignment', 'opt')
        expect(config).to have_key('condition_version')
      end

      it 'omits condition_version when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_marketplace_role_assignment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_marketplace_role_assignment', 'minimal')
        expect(config).not_to have_key('condition_version')
      end
      it 'includes delegated_managed_identity_resource_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_marketplace_role_assignment('opt', required_attrs.merge(delegated_managed_identity_resource_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_marketplace_role_assignment', 'opt')
        expect(config).to have_key('delegated_managed_identity_resource_id')
      end

      it 'omits delegated_managed_identity_resource_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_marketplace_role_assignment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_marketplace_role_assignment', 'minimal')
        expect(config).not_to have_key('delegated_managed_identity_resource_id')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_marketplace_role_assignment('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_marketplace_role_assignment', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_marketplace_role_assignment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_marketplace_role_assignment', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_marketplace_role_assignment('opt', required_attrs.merge(name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_marketplace_role_assignment', 'opt')
        expect(config).to have_key('name')
      end

      it 'omits name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_marketplace_role_assignment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_marketplace_role_assignment', 'minimal')
        expect(config).not_to have_key('name')
      end
      it 'includes role_definition_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_marketplace_role_assignment('opt', required_attrs.merge(role_definition_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_marketplace_role_assignment', 'opt')
        expect(config).to have_key('role_definition_id')
      end

      it 'omits role_definition_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_marketplace_role_assignment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_marketplace_role_assignment', 'minimal')
        expect(config).not_to have_key('role_definition_id')
      end
      it 'includes role_definition_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_marketplace_role_assignment('opt', required_attrs.merge(role_definition_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_marketplace_role_assignment', 'opt')
        expect(config).to have_key('role_definition_name')
      end

      it 'omits role_definition_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_marketplace_role_assignment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_marketplace_role_assignment', 'minimal')
        expect(config).not_to have_key('role_definition_name')
      end
      it 'includes skip_service_principal_aad_check when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_marketplace_role_assignment('opt', required_attrs.merge(skip_service_principal_aad_check: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_marketplace_role_assignment', 'opt')
        expect(config).to have_key('skip_service_principal_aad_check')
      end

      it 'omits skip_service_principal_aad_check when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_marketplace_role_assignment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_marketplace_role_assignment', 'minimal')
        expect(config).not_to have_key('skip_service_principal_aad_check')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts skip_service_principal_aad_check=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(skip_service_principal_aad_check: val)
          synth.azurerm_marketplace_role_assignment("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'azurerm_marketplace_role_assignment', "bool_#{val}")
          expect(config['skip_service_principal_aad_check']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_marketplace_role_assignment('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_marketplace_role_assignment', 'typed')
        expect(config['principal_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_marketplace_role_assignment('first', required_attrs)
        synth.azurerm_marketplace_role_assignment('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_marketplace_role_assignment')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_marketplace_role_assignment,
    method: :azurerm_marketplace_role_assignment,
    required_attrs: { principal_id: 'test-value' },
    expected_outputs: [:id, :principal_type],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:skip_service_principal_aad_check]
end
