# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_app_service_connection resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureAppServiceConnection do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { app_service_id: 'test-value', authentication: { 'key1' => 'val1' }, name: 'test-value', target_resource_id: 'test-value' } }

  describe ':azurerm_app_service_connection' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_app_service_connection('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_app_service_connection', 'test')
        validate_required_attributes(config, [:app_service_id, :authentication, :name, :target_resource_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_app_service_connection('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_app_service_connection)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_app_service_connection('test', required_attrs)

        expect(ref.id).to eq("${azurerm_app_service_connection.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ client_type: 'test-value', secret_store: { 'key1' => 'val1' }, vnet_solution: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_app_service_connection('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_app_service_connection', 'full')
        expect(config).to have_key('client_type')
        expect(config).to have_key('secret_store')
        expect(config).to have_key('vnet_solution')
      end
    end

    context 'optional attributes' do
      it 'includes client_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_app_service_connection('opt', required_attrs.merge(client_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_app_service_connection', 'opt')
        expect(config).to have_key('client_type')
      end

      it 'omits client_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_app_service_connection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_app_service_connection', 'minimal')
        expect(config).not_to have_key('client_type')
      end
      it 'includes secret_store when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_app_service_connection('opt', required_attrs.merge(secret_store: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_app_service_connection', 'opt')
        expect(config).to have_key('secret_store')
      end

      it 'omits secret_store when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_app_service_connection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_app_service_connection', 'minimal')
        expect(config).not_to have_key('secret_store')
      end
      it 'includes vnet_solution when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_app_service_connection('opt', required_attrs.merge(vnet_solution: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_app_service_connection', 'opt')
        expect(config).to have_key('vnet_solution')
      end

      it 'omits vnet_solution when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_app_service_connection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_app_service_connection', 'minimal')
        expect(config).not_to have_key('vnet_solution')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_app_service_connection('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_app_service_connection', 'typed')
        expect(config['app_service_id']).to be_a(String)
        expect(config['authentication']).to be_a(Hash)
        expect(config['name']).to be_a(String)
        expect(config['target_resource_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_app_service_connection('first', required_attrs)
        synth.azurerm_app_service_connection('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_app_service_connection')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_app_service_connection,
    method: :azurerm_app_service_connection,
    required_attrs: { app_service_id: 'test-value', authentication: { 'key1' => 'val1' }, name: 'test-value', target_resource_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
