# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_cosmosdb_sql_role_assignment resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureCosmosdbSqlRoleAssignment do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { account_name: 'test-value', principal_id: 'test-value', resource_group_name: 'test-value', role_definition_id: 'test-value', scope: 'test-value' } }

  describe ':azurerm_cosmosdb_sql_role_assignment' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_cosmosdb_sql_role_assignment('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_cosmosdb_sql_role_assignment', 'test')
        validate_required_attributes(config, [:account_name, :principal_id, :resource_group_name, :role_definition_id, :scope])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_cosmosdb_sql_role_assignment('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_cosmosdb_sql_role_assignment)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_cosmosdb_sql_role_assignment('test', required_attrs)

        expect(ref.id).to eq("${azurerm_cosmosdb_sql_role_assignment.test.id}")
        expect(ref.name).to eq("${azurerm_cosmosdb_sql_role_assignment.test.name}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_cosmosdb_sql_role_assignment('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_cosmosdb_sql_role_assignment', 'test')
        expect(config).not_to have_key('name')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ name: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_cosmosdb_sql_role_assignment('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_cosmosdb_sql_role_assignment', 'full')
        expect(config).to have_key('name')
      end
    end

    context 'optional attributes' do
      it 'includes name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_cosmosdb_sql_role_assignment('opt', required_attrs.merge(name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_cosmosdb_sql_role_assignment', 'opt')
        expect(config).to have_key('name')
      end

      it 'omits name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_cosmosdb_sql_role_assignment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_cosmosdb_sql_role_assignment', 'minimal')
        expect(config).not_to have_key('name')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_cosmosdb_sql_role_assignment('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_cosmosdb_sql_role_assignment', 'typed')
        expect(config['account_name']).to be_a(String)
        expect(config['principal_id']).to be_a(String)
        expect(config['resource_group_name']).to be_a(String)
        expect(config['role_definition_id']).to be_a(String)
        expect(config['scope']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_cosmosdb_sql_role_assignment('first', required_attrs)
        synth.azurerm_cosmosdb_sql_role_assignment('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_cosmosdb_sql_role_assignment')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_cosmosdb_sql_role_assignment,
    method: :azurerm_cosmosdb_sql_role_assignment,
    required_attrs: { account_name: 'test-value', principal_id: 'test-value', resource_group_name: 'test-value', role_definition_id: 'test-value', scope: 'test-value' },
    expected_outputs: [:id, :name],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
