# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_subscription resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureSubscription do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { subscription_name: 'test-value' } }

  describe ':azurerm_subscription' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_subscription('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_subscription', 'test')
        validate_required_attributes(config, [:subscription_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_subscription('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_subscription)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_subscription('test', required_attrs)

        expect(ref.id).to eq("${azurerm_subscription.test.id}")
        expect(ref.alias).to eq("${azurerm_subscription.test.alias}")
        expect(ref.subscription_id).to eq("${azurerm_subscription.test.subscription_id}")
        expect(ref.tenant_id).to eq("${azurerm_subscription.test.tenant_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_subscription('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_subscription', 'test')
        expect(config).not_to have_key('alias')
        expect(config).not_to have_key('subscription_id')
        expect(config).not_to have_key('tenant_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ billing_scope_id: 'test-value', tags: { 'key1' => 'val1' }, workload: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_subscription('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_subscription', 'full')
        expect(config).to have_key('billing_scope_id')
        expect(config).to have_key('tags')
        expect(config).to have_key('workload')
      end
    end

    context 'optional attributes' do
      it 'includes billing_scope_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_subscription('opt', required_attrs.merge(billing_scope_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_subscription', 'opt')
        expect(config).to have_key('billing_scope_id')
      end

      it 'omits billing_scope_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_subscription('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_subscription', 'minimal')
        expect(config).not_to have_key('billing_scope_id')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_subscription('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_subscription', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_subscription('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_subscription', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes workload when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_subscription('opt', required_attrs.merge(workload: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_subscription', 'opt')
        expect(config).to have_key('workload')
      end

      it 'omits workload when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_subscription('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_subscription', 'minimal')
        expect(config).not_to have_key('workload')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_subscription('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_subscription', 'typed')
        expect(config['subscription_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_subscription('first', required_attrs)
        synth.azurerm_subscription('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_subscription')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_subscription,
    method: :azurerm_subscription,
    required_attrs: { subscription_name: 'test-value' },
    expected_outputs: [:id, :alias, :subscription_id, :tenant_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
