# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a azurerm_spring_cloud_application_insights_application_performance_monitoring resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AzureSpringCloudApplicationInsightsApplicationPerformanceMonitoring do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', spring_cloud_service_id: 'test-value' } }

  describe ':azurerm_spring_cloud_application_insights_application_performance_monitoring' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_application_insights_application_performance_monitoring('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_application_insights_application_performance_monitoring', 'test')
        validate_required_attributes(config, [:name, :spring_cloud_service_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_spring_cloud_application_insights_application_performance_monitoring('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:azurerm_spring_cloud_application_insights_application_performance_monitoring)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.azurerm_spring_cloud_application_insights_application_performance_monitoring('test', required_attrs)

        expect(ref.id).to eq("${azurerm_spring_cloud_application_insights_application_performance_monitoring.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ connection_string: 'test-value', globally_enabled: true, role_instance: 'test-value', role_name: 'test-value', sampling_percentage: 3.14, sampling_requests_per_second: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_application_insights_application_performance_monitoring('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_spring_cloud_application_insights_application_performance_monitoring', 'full')
        expect(config).to have_key('connection_string')
        expect(config).to have_key('globally_enabled')
        expect(config).to have_key('role_instance')
        expect(config).to have_key('role_name')
        expect(config).to have_key('sampling_percentage')
        expect(config).to have_key('sampling_requests_per_second')
      end
    end

    context 'optional attributes' do
      it 'includes connection_string when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_application_insights_application_performance_monitoring('opt', required_attrs.merge(connection_string: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_application_insights_application_performance_monitoring', 'opt')
        expect(config).to have_key('connection_string')
      end

      it 'omits connection_string when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_application_insights_application_performance_monitoring('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_application_insights_application_performance_monitoring', 'minimal')
        expect(config).not_to have_key('connection_string')
      end
      it 'includes globally_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_application_insights_application_performance_monitoring('opt', required_attrs.merge(globally_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_application_insights_application_performance_monitoring', 'opt')
        expect(config).to have_key('globally_enabled')
      end

      it 'omits globally_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_application_insights_application_performance_monitoring('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_application_insights_application_performance_monitoring', 'minimal')
        expect(config).not_to have_key('globally_enabled')
      end
      it 'includes role_instance when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_application_insights_application_performance_monitoring('opt', required_attrs.merge(role_instance: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_application_insights_application_performance_monitoring', 'opt')
        expect(config).to have_key('role_instance')
      end

      it 'omits role_instance when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_application_insights_application_performance_monitoring('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_application_insights_application_performance_monitoring', 'minimal')
        expect(config).not_to have_key('role_instance')
      end
      it 'includes role_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_application_insights_application_performance_monitoring('opt', required_attrs.merge(role_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_application_insights_application_performance_monitoring', 'opt')
        expect(config).to have_key('role_name')
      end

      it 'omits role_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_application_insights_application_performance_monitoring('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_application_insights_application_performance_monitoring', 'minimal')
        expect(config).not_to have_key('role_name')
      end
      it 'includes sampling_percentage when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_application_insights_application_performance_monitoring('opt', required_attrs.merge(sampling_percentage: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_application_insights_application_performance_monitoring', 'opt')
        expect(config).to have_key('sampling_percentage')
      end

      it 'omits sampling_percentage when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_application_insights_application_performance_monitoring('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_application_insights_application_performance_monitoring', 'minimal')
        expect(config).not_to have_key('sampling_percentage')
      end
      it 'includes sampling_requests_per_second when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_application_insights_application_performance_monitoring('opt', required_attrs.merge(sampling_requests_per_second: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_application_insights_application_performance_monitoring', 'opt')
        expect(config).to have_key('sampling_requests_per_second')
      end

      it 'omits sampling_requests_per_second when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_application_insights_application_performance_monitoring('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'azurerm_spring_cloud_application_insights_application_performance_monitoring', 'minimal')
        expect(config).not_to have_key('sampling_requests_per_second')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts globally_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(globally_enabled: val)
          synth.azurerm_spring_cloud_application_insights_application_performance_monitoring("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'azurerm_spring_cloud_application_insights_application_performance_monitoring', "bool_#{val}")
          expect(config['globally_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_application_insights_application_performance_monitoring('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'azurerm_spring_cloud_application_insights_application_performance_monitoring', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['spring_cloud_service_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.azurerm_spring_cloud_application_insights_application_performance_monitoring('first', required_attrs)
        synth.azurerm_spring_cloud_application_insights_application_performance_monitoring('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'azurerm_spring_cloud_application_insights_application_performance_monitoring')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :azurerm_spring_cloud_application_insights_application_performance_monitoring,
    method: :azurerm_spring_cloud_application_insights_application_performance_monitoring,
    required_attrs: { name: 'test-value', spring_cloud_service_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:globally_enabled]
end
